## Housekeeping

### Import dependencies and silence warnings

In [ ]:
import polars as pl
from pathlib import Path

from process_data import process_pbp_metadata, aggregate_stints_df
from regressions import build_position_map, build_matrix, run_all_regressions

import chickenstats.utilities

import matplotlib.pyplot as plt

import seaborn as sns

### Polars configuration options

In [ ]:
pl.Config.set_tbl_cols(-1)

polars.config.Config

### Setting up the chickenstats styles

In [ ]:
plt.style.use("chickenstats")

## Illustrative data munging and matrix constructions

### Reading play-by-play data as a lazyframe

In [ ]:
pbp_path = Path("./data/raw/pbp.parquet")

lazy_pbp = pl.scan_parquet(pbp_path)

### Choosing the season(s) for this run

In [ ]:
# Settings the season as the latest full season in the data
seasons = [20242025]

# just so you can see them all
sorted(lazy_pbp.select(pl.col("season")).unique().collect()["season"].to_list())

[20102011,
 20112012,
 20122013,
 20132014,
 20142015,
 20152016,
 20162017,
 20172018,
 20182019,
 20192020,
 20202021,
 20212022,
 20222023,
 20232024,
 20242025]

### Filtering pbp to a single season to show data processing

In [ ]:
# Filtering pbp data to a single season / session combo to illustrate
# what goes in in the background prior to running the regression
conditions = (pl.col("season") == seasons[0], pl.col("session") == "R")
season_pbp = lazy_pbp.filter(conditions).collect()

### Creating the lookup table for back-to-back games

In [ ]:
# Lookup table for back-to-back games, leverages same conditions as the previous cell
meta_lookup = process_pbp_metadata(lazy_pbp.filter(conditions))

### Aggregating to stints-level dataframe

In [ ]:
# Aggregating to the stints-level dataframe, using the season data and the b2b meta lookup table
stints = aggregate_stints_df(pbp_df=season_pbp, meta_lookup=meta_lookup)

In [ ]:
# Showing the stints in order for 2024-25 season
stints.sort(["game_id", "period", "stint_id"], descending=[False, False, False])

shape: (523_450, 34)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sea ┆ ses ┆ gam ┆ per ┆ sti ┆ toi ┆ h_x ┆ a_x ┆ h_c ┆ a_c ┆ h_g ┆ a_g ┆ h_i ┆ a_i ┆ h_g ┆ a_g ┆ h_t ┆ a_t ┆ h_s ┆ h_s ┆ a_s ┆ a_s ┆ h_b ┆ a_b ┆ str ┆ ozs ┆ nzs ┆ dzs ┆ h_s ┆ a_s ┆ h_g ┆ a_g ┆ h_c ┆ a_c │
│ son ┆ sio ┆ e_i ┆ iod ┆ nt_ ┆ --- ┆ gf  ┆ gf  ┆ f   ┆ f   ┆ f   ┆ f   ┆ ds  ┆ ds  ┆ oal ┆ oal ┆ eam ┆ eam ┆ 3   ┆ 7   ┆ 3   ┆ 7   ┆ 2b  ┆ 2b  ┆ eng ┆ --- ┆ --- ┆ --- ┆ kat ┆ kat ┆ oal ┆ oal ┆ nt  ┆ nt  │
│ --- ┆ n   ┆ d   ┆ --- ┆ id  ┆ i64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ie_ ┆ ie_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ th  ┆ boo ┆ boo ┆ boo ┆ ers ┆ ers ┆ ies ┆ ies ┆ --- ┆ --- │
│ i64 ┆ --- ┆ --- ┆ i64 ┆ --- ┆     ┆ f64 ┆ f64 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ lis ┆ lis ┆ ids ┆ ids ┆ str ┆ str ┆ i32 ┆ i64 ┆ i32 ┆ i64 ┆ boo ┆ boo ┆ --- ┆ l   ┆ l   ┆ l   ┆ --- ┆ --- ┆ --- ┆ --- ┆ u32 ┆ u32 │
│     ┆ str ┆ i64 ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆ t[s ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ str ┆     ┆     ┆     ┆ lis ┆ lis ┆ lis ┆ lis ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆ tr] ┆ lis ┆ lis ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆ t[s ┆ t[s ┆ t[s ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t[s ┆ t[s ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆ tr] ┆ tr] ┆ tr] ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tr] ┆ tr] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ R   ┆ 202 ┆ 1   ┆ 6   ┆ 21  ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ BUF ┆ NJD ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ tru ┆ fal ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆ 122 ┆     ┆     ┆     ┆     ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ se  ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     │
│ 25  ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆ 13  ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "RA ┆ ,   ┆ N"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "RA ┆ ,   ┆ N"] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SMU ┆ "SI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SMU ┆ "SI ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S.D ┆ MON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ S.D ┆ MON ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A…  ┆ .…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ A…  ┆ .…  ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 1   ┆ 8   ┆ 1   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ BUF ┆ NJD ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     │
│ 25  ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 1   ┆ 9   ┆ 1   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ BUF ┆ NJD ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     │
│ 25  ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 1   ┆ 11  ┆ 6   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ BUF ┆ NJD ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["H ┆ ["J ┆ ["U ┆ ["J ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆ 193 ┆     ┆     ┆     ┆     ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ ENR ┆ ONA ┆ KKO ┆ ACO ┆     ┆     │
│ 25  ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆ 22  ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ S.S ┆ -PE ┆ B.M ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ IEG ┆ KKA ┆ ARK ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ENT ┆ .LU ┆ STR ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ HAL ┆ UKK ┆ OM" ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ER" ┆ ONE ┆ ]   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ ,   ┆ N"] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ "SI ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ MON ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ .…  ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 1   ┆ 12  ┆ 4   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ ["H ┆ ["D ┆ ["U ┆ ["J ┆ BUF ┆ NJD ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["H ┆ ["D ┆ ["U ┆ ["J ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ENR ┆ OUG ┆ KKO ┆ ACO ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ ENR ┆ OUG ┆ KKO ┆ ACO ┆     ┆     │
│ 25  ┆     ┆ 000 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ IE. ┆ -PE ┆ B.M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ I.J ┆ IE. ┆ -PE ┆ B.M ┆     ┆     │
│     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ HAM ┆ KKA ┆ ARK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OKI ┆ HAM ┆ KKA ┆ ARK ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ILT ┆ .LU ┆ STR ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ HAR ┆ ILT ┆ .LU ┆ STR ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ ON" ┆ UKK ┆ OM" ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ JU" ┆ ON" ┆ UKK ┆ OM" ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ,   ┆ ONE ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,   ┆ ,   ┆ ONE ┆ ]   ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ "SI ┆ N"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "BO ┆ "SI ┆ N"] ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ MON ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ WEN ┆ MON ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ .NE ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .BY ┆ .NE ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ M…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ R…  ┆ M…  ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ R   ┆ 202 ┆ 3   ┆ 144 ┆ 1   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ CBJ ┆ NYI ┆ 1   ┆ 3   ┆ -1  ┆ -3  ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆ 225 ┆     ┆     ┆     ┆     ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     │
│ 25  ┆     ┆ 131 ┆     ┆     ┆     ┆     ┆ 54  ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     │
│     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "TO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "TO ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ NY. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ NY. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N.M ┆ DEA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N.M ┆ DEA ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATE ┆ NG… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATE ┆ NG… ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 3   ┆ 146 ┆ 1   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ CBJ ┆ NYI ┆ 1   ┆ 3   ┆ -1  ┆ -3  ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     │
│ 25  ┆     ┆ 131 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     │
│     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "TO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "TO ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ NY. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ NY. ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N.M ┆ DEA ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ N.M ┆ DEA ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATE ┆ NG… ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ATE ┆ NG… ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ 202 ┆ 3   ┆ 147 ┆ 2   ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ CBJ ┆ NYI ┆ 1   ┆ 3   ┆ -1  ┆ -3  ┆ fal ┆ fal ┆ 5v5 ┆ fal ┆ fal ┆ fal ┆ ["I ┆ ["S ┆ ["J ┆ ["M ┆ 5   ┆ 5   │
│ 420 ┆     ┆ 402 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆     ┆ se  ┆ se  ┆ se  ┆ VAN ┆ COT ┆ ET. ┆ ARC ┆     ┆     │
│ 25  ┆     ┆ 131 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .PR ┆ T.M ┆ GRE ┆ US. ┆     ┆     │
│     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ OVO ┆ AYF ┆ AVE ┆ HOG ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ROV ┆ IEL ┆ S"] ┆ BER ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ",  ┆ D", ┆     ┆ G"] ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "SC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ "DE ┆ "SC ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ OTT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ NTO ┆ OTT ┆     ┆     ┆     ┆     │

### Building the regression matrix, target / weights numpy arrays, full skater list, and the player metrics for that season

In [ ]:
# Function returns a bunch of different data for us
X, Y, W, skater_list, player_metrics = build_matrix(stints)

### Sparse matrix for running the regressions

In [ ]:
# The sparse matrix used in the ridge regression only stores the 1 values,
# with the x coordinates indicating the index of the stint and the y-coordinates
# indicating the players who are on-ice offensive / defensively
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 11401669 stored elements and shape (923652, 2067)>
  Coords	Values
  (0, 128)	1.0
  (0, 240)	1.0
  (0, 437)	1.0
  (0, 467)	1.0
  (0, 782)	1.0
  (0, 1483)	1.0
  (0, 1502)	1.0
  (0, 1612)	1.0
  (0, 1652)	1.0
  (0, 1716)	1.0
  (0, 2056)	1.0
  (0, 2063)	1.0
  (0, 2066)	1.0
  (1, 169)	1.0
  (1, 457)	1.0
  (1, 528)	1.0
  (1, 774)	1.0
  (1, 860)	1.0
  (1, 1029)	1.0
  (1, 1342)	1.0
  (1, 1419)	1.0
  (1, 1566)	1.0
  (1, 1828)	1.0
  (1, 2056)	1.0
  (1, 2063)	1.0
  :	:
  (923649, 2056)	1.0
  (923649, 2065)	1.0
  (923650, 88)	1.0
  (923650, 207)	1.0
  (923650, 299)	1.0
  (923650, 479)	1.0
  (923650, 747)	1.0
  (923650, 1463)	1.0
  (923650, 1613)	1.0
  (923650, 1721)	1.0
  (923650, 1744)	1.0
  (923650, 1954)	1.0
  (923650, 2056)	1.0
  (923651, 33)	1.0
  (923651, 449)	1.0
  (923651, 708)	1.0
  (923651, 791)	1.0
  (923651, 864)	1.0
  (923651, 1072)	1.0
  (923651, 1428)	1.0
  (923651, 1583)	1.0
  (923651, 1822)	1.0
  (923651, 1970)	1.0
  (923651, 2056)	1.0
  (923651, 2066)	1.0

### Numpy array of the target metric, in this case xG / 60

In [ ]:
# Array of stint-level xG / 60, used in the ridge regression
print(Y)

[0. 0. 0. ... 0. 0. 0.]

### Numpy array of the weights, which are time-on-ice

In [ ]:
# Array of the stint-level time-on-ice
print(W)

[ 1  2  9 ... 10  3  1]

### List of skaters that season who had more than the time-on-ice minimum (in this case, one minute)

In [ ]:
# All of the skaters who appear on the ice for more than one minute, aggregated by team
skater_list

['A.J.GREER_FLA',
 'AARON.EKBLAD_FLA',
 'AATU.RATY_VAN',
 'ADAM.BOQVIST_FLA',
 'ADAM.BOQVIST_NYI',
 'ADAM.EDSTROM_NYR',
 'ADAM.FANTILLI_CBJ',
 'ADAM.FOX_NYR',
 'ADAM.GAUDETTE_OTT',
 'ADAM.GINNING_PHI',
 'ADAM.HENRIQUE_EDM',
 'ADAM.KLAPKA_CGY',
 'ADAM.LARSSON_SEA',
 'ADAM.LOWRY_WPG',
 'ADAM.PELECH_NYI',
 'ADAM.WILSBY_NSH',
 'ADRIAN.KEMPE_LAK',
 'AKIL.THOMAS_LAK',
 'ALBERT.JOHANSSON_DET',
 'ALEC.MARTINEZ_CHI',
 'ALEKSANDER.BARKOV_FLA',
 'ALEX.BARRE-BOULET_MTL',
 'ALEX.DEBRINCAT_DET',
 'ALEX.IAFALLO_WPG',
 'ALEX.KILLORN_ANA',
 'ALEX.LAFERRIERE_LAK',
 'ALEX.NEWHOOK_MTL',
 'ALEX.NYLANDER_TOR',
 'ALEX.OVECHKIN_WSH',
 'ALEX.PIETRANGELO_VGK',
 'ALEX.STEEVES_TOR',
 'ALEX.TUCH_BUF',
 'ALEX.TURCOTTE_LAK',
 'ALEX.VLASIC_CHI',
 'ALEXANDER.ALEXEYEV_WSH',
 'ALEXANDER.HOLTZ_VGK',
 'ALEXANDER.KERFOOT_UTA',
 'ALEXANDER.PETROVIC_DAL',
 'ALEXANDER.ROMANOV_NYI',
 'ALEXANDER.WENNBERG_SJS',
 'ALEXANDRE.CARRIER_MTL',
 'ALEXANDRE.CARRIER_NSH',
 'ALEXANDRE.TEXIER_STL',
 'ALEXEI.TOROPCHENKO_STL',
 'ALEXIS.LAFRENIERE_NYR',
 'ALIAKSEI.PROTAS_WSH',
 'ANDERS.LEE_NYI',
 'ANDRE.BURAKOVSKY_SEA',
 'ANDRE.LEE_LAK',
 'ANDREAS.ATHANASIOU_CHI',
 'ANDREAS.ENGLUND_LAK',
 'ANDREAS.ENGLUND_NSH',
 'ANDREI.KUZMENKO_CGY',
 'ANDREI.KUZMENKO_LAK',
 'ANDREI.KUZMENKO_PHI',
 'ANDREI.SVECHNIKOV_CAR',
 'ANDREW.COPP_DET',
 'ANDREW.MANGIAPANE_WSH',
 'ANDREW.PEEKE_BOS',
 'ANDREW.POTURALSKI_SJS',
 'ANGUS.CROOKSHANK_OTT',
 'ANTHONY.BEAUVILLIER_PIT',
 'ANTHONY.BEAUVILLIER_WSH',
 'ANTHONY.CIRELLI_TBL',
 'ANTHONY.DUCLAIR_NYI',
 'ANTHONY.MANTHA_CGY',
 'ANTHONY.RICHARD_PHI',
 'ANTON.LUNDELL_FLA',
 'ANZE.KOPITAR_LAK',
 'ARBER.XHEKAJ_MTL',
 'ARSHDEEP.BAINS_VAN',
 'ARTEM.ZUB_OTT',
 'ARTEMI.PANARIN_NYR',
 'ARTHUR.KALIYEV_NYR',
 'ARTTU.HYRY_DAL',
 'ARTTURI.LEHKONEN_COL',
 'ARTYOM.LEVSHUNOV_CHI',
 'AUSTIN.WATSON_DET',
 'AUSTON.MATTHEWS_TOR',
 'AYDAR.SUNIEV_CGY',
 'BARCLAY.GOODROW_SJS',
 'BARRETT.HAYTON_UTA',
 'BECK.MALENSTYN_BUF',
 'BEN.CHIAROT_DET',
 'BEN.HUTTON_VGK',
 'BEN.JONES_MIN',
 'BEN.MEYERS_SEA',
 'BLAKE.COLEMAN_CGY',
 'BLAKE.LIZOTTE_PIT',
 'BO.HORVAT_NYI',
 'BOBBY.BRINK_PHI',
 'BOBBY.MCMANN_TOR',
 'BOKONDJI.IMAMA_PIT',
 'BOONE.JENNER_CBJ',
 'BOWEN.BYRAM_BUF',
 'BRAD.LAMBERT_WPG',
 'BRAD.MARCHAND_BOS',
 'BRAD.MARCHAND_FLA',
 'BRADEN.SCHNEIDER_NYR',
 'BRADLY.NADEAU_CAR',
 'BRADY.SKJEI_NSH',
 'BRADY.TKACHUK_OTT',
 'BRANDON.CARLO_BOS',
 'BRANDON.CARLO_TOR',
 'BRANDON.DUHAIME_WSH',
 'BRANDON.HAGEL_TBL',
 'BRANDON.MONTOUR_SEA',
 'BRANDON.SAAD_STL',
 'BRANDON.SAAD_VGK',
 'BRANDON.TANEV_SEA',
 'BRANDON.TANEV_WPG',
 'BRANDT.CLARKE_LAK',
 'BRAYDEN.MCNABB_VGK',
 'BRAYDEN.PACHAL_CGY',
 'BRAYDEN.POINT_TBL',
 'BRAYDEN.SCHENN_STL',
 'BRENDAN.BRISSON_VGK',
 'BRENDAN.GALLAGHER_MTL',
 'BRENDAN.GAUNCE_MIN',
 'BRENDAN.SMITH_DAL',
 'BRENDEN.DILLON_NJD',
 'BRENNAN.OTHMANN_NYR',
 'BRENT.BURNS_CAR',
 'BRETT.BERARD_NYR',
 'BRETT.HOWDEN_VGK',
 'BRETT.KULAK_EDM',
 'BRETT.LEASON_ANA',
 'BRETT.MURRAY_BUF',
 'BRETT.PESCE_NJD',
 'BRIAN.DUMOULIN_ANA',
 'BRIAN.DUMOULIN_NJD',
 'BRIAN.HALONEN_NJD',
 'BROCK.BOESER_VAN',
 'BROCK.FABER_MIN',
 'BROCK.MCGINN_ANA',
 'BROCK.NELSON_COL',
 'BROCK.NELSON_NYI',
 'BRYAN.RUST_PIT',
 'CALE.FLEURY_SEA',
 'CALE.MAKAR_COL',
 'CALEB.JONES_LAK',
 'CALLAHAN.BURKE_VGK',
 'CALLE.JARNKROK_TOR',
 'CALUM.RITCHIE_COL',
 'CALVIN.DE HAAN_COL',
 'CALVIN.DE HAAN_NYR',
 'CAM.ATKINSON_TBL',
 'CAM.DINEEN_EDM',
 'CAM.FOWLER_ANA',
 'CAM.FOWLER_STL',
 'CAM.LUND_SJS',
 'CAM.YORK_PHI',
 'CAMERON.CROTTY_MIN',
 'CARL.GRUNDSTROM_SJS',
 'CARSON.SOUCY_NYR',
 'CARSON.SOUCY_VAN',
 'CARTER.MAZUR_DET',
 'CARTER.VERHAEGHE_FLA',
 'CASEY.CIZIKAS_NYI',
 'CASEY.MITTELSTADT_BOS',
 'CASEY.MITTELSTADT_COL',
 'CHAD.RUHWEDEL_NYR',
 'CHANDLER.STEPHENSON_SEA',
 'CHARLIE.COYLE_BOS',
 'CHARLIE.COYLE_COL',
 'CHARLIE.MCAVOY_BOS',
 'CHASE.BRADLEY_COL',
 'CHRIS.KREIDER_NYR',
 'CHRIS.TANEV_TOR',
 'CHRIS.WAGNER_COL',
 'CHRISTIAN.DVORAK_MTL',
 'CHRISTIAN.FISCHER_CBJ',
 'CHRISTIAN.FISCHER_DET',
 'CLARK.BISHOP_CGY',
 'CLAUDE.GIROUX_OTT',
 'CLAYTON.KELLER_UTA',
 'CODY.CECI_DAL',
 'CODY.CECI_SJS',
 'CODY.GLASS_NJD',
 'CODY.GLASS_PIT',
 'COLE.CAUFIELD_MTL',
 'COLE.KOEPKE_BOS',
 'COLE.PERFETTI_WPG',
 'COLE.REINHARDT_OTT',
 'COLE.SCHWINDT_VGK',
 'COLE.SILLINGER_CBJ',
 'COLE.SMITH_NSH',
 'COLIN.BLACKWELL_DAL',
 'COLIN.MILLER_WPG',
 'COLIN.WHITE2_SJS',
 'COLLIN.GRAF_SJS',
 'COLTON.DACH_CHI',
 'COLTON.PARAYKO_STL',
 'COLTON.SISSONS_NSH',
 'CONNOR.BEDARD_CHI',
 'CONNOR.BROWN_EDM',
 'CONNOR.CLIFTON_BUF',
 'CONNOR.DEWAR_PIT',
 'CONNOR.DEWAR_TOR',
 'CONNOR.MACKEY_NYR',
 'CONNOR.MCDAVID_EDM',
 'CONNOR.MCMICHAEL_WSH',
 'CONNOR.MURPHY_CHI',
 'CONNOR.ZARY_CGY',
 'CONOR.GARLAND_VAN',
 'CONOR.GEEKIE_TBL',
 'CONOR.SHEARY_TBL',
 'CONOR.TIMMINS_PIT',
 'CONOR.TIMMINS_TOR',
 'COREY.PERRY_EDM',
 'COREY.SCHUENEMAN_STL',
 'CRAIG.SMITH_CHI',
 'CRAIG.SMITH_DET',
 'CURTIS.LAZAR_NJD',
 'CUTTER.GAUTHIER_ANA',
 'DAEMON.HUNT_MIN',
 'DAKOTA.JOSHUA_VAN',
 'DAKOTA.MERMIS_TOR',
 'DAKOTA.MERMIS_UTA',
 'DALIBOR.DVORSKY_STL',
 'DAMON.SEVERSON_CBJ',
 'DANIEL.SPRONG_NJD',
 'DANIEL.SPRONG_SEA',
 'DANIEL.SPRONG_VAN',
 'DANIIL.MIROMANOV_CGY',
 'DANIIL.MISYUL_NJD',
 'DANIL.GUSHCHIN_SJS',
 'DANTE.FABBRO_CBJ',
 'DANTE.FABBRO_NSH',
 'DANTON.HEINEN_PIT',
 'DANTON.HEINEN_VAN',
 'DARNELL.NURSE_EDM',
 'DARREN.RADDYSH_TBL',
 'DAVID.GUSTAFSSON_WPG',
 'DAVID.JIRICEK_CBJ',
 'DAVID.JIRICEK_MIN',
 'DAVID.KAMPF_TOR',
 'DAVID.PASTRNAK_BOS',
 'DAVID.PERRON_OTT',
 'DAVID.SAVARD_MTL',
 'DAWSON.MERCER_NJD',
 'DECLAN.CARLILE_TBL',
 'DECLAN.CHISHOLM_MIN',
 'DENNIS.CHOLOWSKI_NJD',
 'DENNIS.CHOLOWSKI_NYI',
 'DENNIS.GILBERT_BUF',
 'DENNIS.GILBERT_OTT',
 'DENTON.MATEYCHUK_CBJ',
 'DEREK.FORBORT_VAN',
 'DEREK.RYAN_EDM',
 'DEVIN.KAPLAN_PHI',
 'DEVIN.SHORE_MIN',
 'DEVON.TOEWS_COL',
 'DMITRI.VORONKOV_CBJ',
 'DMITRY.KULIKOV_FLA',
 'DMITRY.ORLOV_CAR',
 'DOMENICK.FENSORE_CAR',
 'DOMINIC.TONINATO_WPG',
 'DOMINIK.SHINE_DET',
 'DONOVAN.SEBRANGO_OTT',
 'DOUGIE.HAMILTON_NJD',
 'DRAKE.BATHERSON_OTT',
 'DRAKE.CAGGIULA_EDM',
 'DREW.DOUGHTY_LAK',
 'DREW.HELLESON_ANA',
 "DREW.O'CONNOR_PIT",
 "DREW.O'CONNOR_VAN",
 'DRYDEN.HUNT_CGY',
 'DYLAN.COGHLAN_WPG',
 'DYLAN.COZENS_BUF',
 'DYLAN.COZENS_OTT',
 'DYLAN.DEMELO_WPG',
 'DYLAN.DUKE_TBL',
 'DYLAN.GUENTHER_UTA',
 'DYLAN.HOLLOWAY_STL',
 'DYLAN.LARKIN_DET',
 'DYLAN.MCILRATH_WSH',
 'DYLAN.SAMBERG_WPG',
 'DYLAN.STROME_WSH',
 'EELI.TOLVANEN_SEA',
 'EETU.LUOSTARINEN_FLA',
 'EGOR.CHINAKHOV_CBJ',
 'EGOR.ZAMULA_PHI',
 'ELIAS.LINDHOLM_BOS',
 'ELIAS.PETTERSSON2_VAN',
 'ELIAS.PETTERSSON_VAN',
 'ELMER.SODERBLOM_DET',
 'EMIL.ANDRAE_PHI',
 'EMIL.BEMSTROM_PIT',
 'EMIL.HEINEMAN_MTL',
 'EMIL.LILLEBERG_TBL',
 'ERIC.ROBINSON_CAR',
 'ERIK.BRANNSTROM_VAN',
 'ERIK.CERNAK_TBL',
 'ERIK.GUDBRANSON_CBJ',
 'ERIK.GUSTAFSSON2_DET',
 'ERIK.HAULA_NJD',
 'ERIK.JOHNSON_COL',
 'ERIK.JOHNSON_PHI',
 'ERIK.KARLSSON_PIT',
 'ESA.LINDELL_DAL',
 'ETHAN.CARDWELL_SJS',
 'ETHAN.DEL MASTRO_CHI',
 'ETHEN.FRANK_WSH',
 'EVAN.BOUCHARD_EDM',
 'EVAN.RODRIGUES_FLA',
 'EVGENI.MALKIN_PIT',
 'EVGENY.DADONOV_DAL',
 'FABIAN.LYSELL_BOS',
 'FABIAN.ZETTERLUND_OTT',
 'FABIAN.ZETTERLUND_SJS',
 'FEDOR.SVECHKOV_NSH',
 'FILIP.CHYTIL_NYR',
 'FILIP.CHYTIL_VAN',
 'FILIP.FORSBERG_NSH',
 'FILIP.HRONEK_VAN',
 'FRANK.NAZAR_CHI',
 'FRANK.VATRANO_ANA',
 'FRASER.MINTEN_BOS',
 'FRASER.MINTEN_TOR',
 'FREDERIC.BRUNET_BOS',
 'FREDERICK.GAUDREAU_MIN',
 'GABE.PERREAULT_NYR',
 'GABRIEL.VILARDI_WPG',
 'GAGE.GONCALVES_TBL',
 'GARNET.HATHAWAY_PHI',
 'GEORGII.MERKULOV_BOS',
 'GIVANI.SMITH_COL',
 'GIVANI.SMITH_SJS',
 'GRANT.HUTTON_NYI',
 'GRIGORI.DENISENKO_VGK',
 'GUILLAUME.BRISEBOIS_VAN',
 'GUSTAV.FORSLING_FLA',
 'GUSTAV.NYQUIST_MIN',
 'GUSTAV.NYQUIST_NSH',
 'HAMPUS.LINDHOLM_BOS',
 'HAYDEN.HODGSON_OTT',
 'HAYDN.FLEURY_WPG',
 'HELGE.GRANS_PHI',
 'HENDRIX.LAPIERRE_WSH',
 'HENRI.JOKIHARJU_BOS',
 'HENRI.JOKIHARJU_BUF',
 'HENRY.THRUN_SJS',
 'HUDSON.FASCHING_NYI',
 'HUNTER.BRZUSTEWICZ_CGY',
 'IAN.COLE_UTA',
 'IAN.MITCHELL_BOS',
 'IAN.MOORE_ANA',
 'ILYA.LYUBUSHKIN_DAL',
 'ILYA.MIKHEYEV_CHI',
 'ILYA.SOLOVYOV_CGY',
 'ISAAK.PHILLIPS_CHI',
 'ISAC.LUNDESTROM_ANA',
 'ISAIAH.GEORGE_NYI',
 'ISAK.ROSEN_BUF',
 'IVAN.BARBASHEV_VGK',
 'IVAN.DEMIDOV_MTL',
 'IVAN.IVAN_COL',
 'IVAN.MIROSHNICHENKO_WSH',
 'IVAN.PROVOROV_CBJ',
 'J.T.COMPHER_DET',
 'J.T.MILLER_NYR',
 'J.T.MILLER_VAN',
 'JACCOB.SLAVIN_CAR',
 'JACK.AHCAN_COL',
 'JACK.DRURY_CAR',
 'JACK.DRURY_COL',
 'JACK.EICHEL_VGK',
 'JACK.FINLEY_TBL',
 'JACK.HUGHES_NJD',
 'JACK.JOHNSON_CBJ',
 'JACK.MCBAIN_UTA',
 'JACK.QUINN_BUF',
 'JACK.ROSLOVIC_CAR',
 'JACK.ST. IVANY_PIT',
 'JACK.THOMPSON_SJS',
 'JACK.WILLIAMS_CBJ',
 'JACKSON.BLAKE_CAR',
 'JACKSON.LACOMBE_ANA',
 'JACOB.BERNARD-DOCKER_BUF',
 'JACOB.BERNARD-DOCKER_OTT',
 'JACOB.BRYSON_BUF',
 'JACOB.GAUCHER_PHI',
 'JACOB.MELANSON_SEA',
 'JACOB.MIDDLETON_MIN',
 'JACOB.MOVERARE_LAK',
 'JACOB.QUILLAN_TOR',
 'JACOB.TROUBA_ANA',
 'JACOB.TROUBA_NYR',
 'JADEN.SCHWARTZ_SEA',
 'JAKE.BEAN_CGY',
 'JAKE.CHRISTIANSEN_CBJ',
 'JAKE.DEBRUSK_VAN',
 'JAKE.EVANS_MTL',
 'JAKE.GUENTZEL_TBL',
 'JAKE.LUCCHINI_NSH',
 'JAKE.MCCABE_TOR',
 'JAKE.NEIGHBOURS_STL',
 'JAKE.SANDERSON_OTT',
 'JAKE.WALMAN_EDM',
 'JAKE.WALMAN_SJS',
 'JAKOB.CHYCHRUN_WSH',
 'JAKOB.PELLETIER_CGY',
 'JAKOB.PELLETIER_PHI',
 'JAKUB.LAUKO_BOS',
 'JAKUB.LAUKO_MIN',
 'JAKUB.VRANA_NSH',
 'JAKUB.VRANA_WSH',
 'JALEN.CHATFIELD_CAR',
 'JAMES.MALATESTA_CBJ',
 'JAMES.VAN RIEMSDYK_CBJ',
 'JAMIE.BENN_DAL',
 'JAMIE.DRYSDALE_PHI',
 'JAMIE.OLEKSIAK_SEA',
 'JAN.JENIK_OTT',
 'JAN.RUTTA_SJS',
 'JANI.HAKANPAA_TOR',
 'JANI.NYMAN_SEA',
 'JANIS.MOSER_TBL',
 'JANSEN.HARKINS_ANA',
 'JARED.MCCANN_SEA',
 'JARED.SPURGEON_MIN',
 'JARET.ANDERSON-DOLAN_WPG',
 'JASON.DICKINSON_CHI',
 'JASON.POLIN_COL',
 'JASON.ROBERTSON_DAL',
 'JASON.ZUCKER_BUF',
 'JAYCOB.MEGNA_FLA',
 'JAYDEN.STRUBLE_MTL',
 'JEAN-GABRIEL.PAGEAU_NYI',
 'JEFF.MALOTT_LAK',
 'JEFF.PETRY_DET',
 'JEFF.SKINNER_EDM',
 'JEFFREY.VIEL_BOS',
 'JERE.INNALA_COL',
 'JEREMY.LAUZON_NSH',
 'JESPER.BOQVIST_FLA',
 'JESPER.BRATT_NJD',
 'JESPERI.KOTKANIEMI_CAR',
 'JESSE.PULJUJARVI_FLA',
 'JESSE.PULJUJARVI_PIT',
 'JETT.LUCHANKO_PHI',
 'JIMMY.SCHULDT_SJS',
 'JIMMY.SNUGGERUD_STL',
 'JIMMY.VESEY_COL',
 'JIMMY.VESEY_NYR',
 'JIRI.KULICH_BUF',
 'JJ.PETERKA_BUF',
 'JOAKIM.KEMELL_NSH',
 'JOE.VELENO_CHI',
 'JOE.VELENO_DET',
 'JOEL.ARMIA_MTL',
 'JOEL.EDMUNDSON_LAK',
 'JOEL.ERIKSSON EK_MIN',
 'JOEL.FARABEE_CGY',
 'JOEL.FARABEE_PHI',
 'JOEL.HANLEY_CGY',
 'JOEL.KIVIRANTA_COL',
 'JOEY.ANDERSON_CHI',
 'JOHN.BEECHER_BOS',
 'JOHN.CARLSON_WSH',
 'JOHN.FARINACCI_BOS',
 'JOHN.HAYDEN_SEA',
 'JOHN.KLINGBERG_EDM',
 'JOHN.LUDVIG_COL',
 'JOHN.MARINO_UTA',
 'JOHN.TAVARES_TOR',
 'JOHNATHAN.KOVACEVIC_NJD',
 'JON.MERRILL_MIN',
 'JONAH.GADJOVICH_FLA',
 'JONAS.BRODIN_MIN',
 'JONAS.RONDBJERG_VGK',
 'JONAS.SIEGENTHALER_NJD',
 'JONATAN.BERGGREN_DET',
 'JONATHAN.DROUIN_COL',
 'JONATHAN.HUBERDEAU_CGY',
 'JONATHAN.LEKKERIMAKI_VAN',
 'JONATHAN.MARCHESSAULT_NSH',
 'JONNY.BRODZINSKI_NYR',
 'JOONA.KOPPANEN_PIT',
 'JORDAN.EBERLE_SEA',
 'JORDAN.GREENWAY_BUF',
 'JORDAN.HARRIS_CBJ',
 'JORDAN.KYROU_STL',
 'JORDAN.MARTINOOK_CAR',
 'JORDAN.OESTERLE_BOS',
 'JORDAN.OESTERLE_NSH',
 'JORDAN.SPENCE_LAK',
 'JORDAN.STAAL_CAR',
 'JOSEPH.LABATE_CBJ',
 'JOSH.ANDERSON_MTL',
 'JOSH.DOAN_UTA',
 'JOSH.MANSON_COL',
 'JOSH.MORRISSEY_WPG',
 'JOSH.NORRIS_BUF',
 'JOSH.NORRIS_OTT',
 'JOSHUA.BROWN_EDM',
 'JOSHUA.DUNNE_BUF',
 'JOSHUA.MAHURA_SEA',
 'JOSHUA.ROY_MTL',
 'JUHA.JAASKA_CAR',
 'JULIEN.GAUTHIER_NYI',
 'JURAJ.SLAFKOVSKY_MTL',
 'JUSTIN.BARRON_MTL',
 'JUSTIN.BARRON_NSH',
 'JUSTIN.BRAZEAU_BOS',
 'JUSTIN.BRAZEAU_MIN',
 'JUSTIN.DANFORTH_CBJ',
 'JUSTIN.DOWLING_NJD',
 'JUSTIN.FAULK_STL',
 'JUSTIN.HOLL_DET',
 'JUSTIN.HRYCKOWIAN_DAL',
 'JUSTIN.KIRKLAND_CGY',
 'JUSTIN.ROBIDAS_CAR',
 'JUSTIN.SOURDIF_FLA',
 'JUUSO.PARSSINEN_COL',
 'JUUSO.PARSSINEN_NSH',
 'JUUSO.PARSSINEN_NYR',
 'JUUSO.VALIMAKI_UTA',
 "K'ANDRE.MILLER_NYR",
 'KAAPO.KAKKO_NYR',
 'KAAPO.KAKKO_SEA',
 'KAEDAN.KORCZAK_VGK',
 'KAIDEN.GUHLE_MTL',
 'KAILER.YAMAMOTO_UTA',
 'KARSEN.DORWART_PHI',
 'KASPERI.KAPANEN_EDM',
 'KASPERI.KAPANEN_STL',
 'KEATON.MIDDLETON_COL',
 'KEEGAN.KOLESAR_VGK',
 'KENT.JOHNSON_CBJ',
 'KEVIN.BAHL_CGY',
 'KEVIN.FIALA_LAK',
 'KEVIN.GRAVEL_NSH',
 'KEVIN.HAYES_PIT',
 'KEVIN.KORCHINSKI_CHI',
 'KEVIN.LABANC_CBJ',
 'KEVIN.ROONEY_CGY',
 'KEVIN.STENLUND_UTA',
 'KIEFER.SHERWOOD_VAN',
 'KIEFFER.BELLOWS_NSH',
 'KIRBY.DACH_MTL',
 'KIRILL.KAPRIZOV_MIN',
 'KIRILL.KUDRYAVTSEV_VAN',
 'KIRILL.MARCHENKO_CBJ',
 'KLIM.KOSTIN_SJS',
 'KRIS.LETANG_PIT',
 'KURTIS.MACDERMID_NJD',
 'KYLE.BURROUGHS_LAK',
 'KYLE.CAPOBIANCO_DAL',
 'KYLE.CONNOR_WPG',
 'KYLE.MACLEAN_NYI',
 'KYLE.PALMIERI_NYI',
 'LANDON.SLAGGERT_CHI',
 'LANE.HUTSON_MTL',
 'LARS.ELLER_PIT',
 'LARS.ELLER_WSH',
 'LAWSON.CROUSE_UTA',
 'LEO.CARLSSON_ANA',
 'LEON.DRAISAITL_EDM',
 'LIAM.FOUDY_NYI',
 "LIAM.O'BRIEN_UTA",
 'LIAM.OHGREN_MIN',
 'LIAN.BICHSEL_DAL',
 'LINUS.KARLSSON_VAN',
 'LOGAN.COOLEY_UTA',
 'LOGAN.MAILLOUX_MTL',
 "LOGAN.O'CONNOR_COL",
 'LOGAN.STANKOVEN_CAR',
 'LOGAN.STANKOVEN_DAL',
 'LOGAN.STANLEY_WPG',
 'LOUIS.CREVIER_CHI',
 'LUCA.CAGNONI_SJS',
 'LUCA.DEL BEL BELLUZ_CBJ',
 'LUCAS.CARLSSON_SJS',
 'LUCAS.CONDOTTA_MTL',
 'LUCAS.RAYMOND_DET',
 'LUKAS.REICHEL_CHI',
 'LUKE.EVANGELISTA_NSH',
 'LUKE.GLENDENING_TBL',
 'LUKE.HUGHES_NJD',
 'LUKE.KUNIN_CBJ',
 'LUKE.KUNIN_SJS',
 'LUKE.SCHENN_NSH',
 'LUKE.SCHENN_WPG',
 'MACKENZIE.WEEGAR_CGY',
 'MACKIE.SAMOSKEVICH_FLA',
 'MACKLIN.CELEBRINI_SJS',
 'MARAT.KHUSNUTDINOV_BOS',
 'MARAT.KHUSNUTDINOV_MIN',
 'MARC-EDOUARD.VLASIC_SJS',
 'MARC.DEL GAIZO_NSH',
 'MARC.GATCOMB_NYI',
 'MARC.MCLAUGHLIN_BOS',
 'MARC.MCLAUGHLIN_NJD',
 'MARCO.KASPER_DET',
 'MARCO.ROSSI_MIN',
 'MARCUS.FOLIGNO_MIN',
 'MARCUS.JOHANSSON_MIN',
 'MARCUS.PETTERSSON_PIT',
 'MARCUS.PETTERSSON_VAN',
 'MARIO.FERRARO_SJS',
 'MARK.FRIEDMAN_VAN',
 'MARK.JANKOWSKI_CAR',
 'MARK.JANKOWSKI_NSH',
 'MARK.KASTELIC_BOS',
 'MARK.SCHEIFELE_WPG',
 'MARK.STONE_VGK',
 'MARTIN.FEHERVARY_WSH',
 'MARTIN.NECAS_CAR',
 'MARTIN.NECAS_COL',
 'MARTIN.POSPISIL_CGY',
 'MASON.APPLETON_WPG',
 'MASON.LOHREI_BOS',
 'MASON.MARCHMENT_DAL',
 'MASON.MCTAVISH_ANA',
 'MASON.MORELLI_VGK',
 'MATEJ.BLUMEL_DAL',
 'MATHEW.BARZAL_NYI',
 'MATHIEU.JOSEPH_STL',
 'MATHIEU.OLIVIER_CBJ',
 'MATIAS.MACCELLI_UTA',
 'MATS.ZUCCARELLO_MIN',
 'MATT.BENNING_SJS',
 'MATT.BOLDY_MIN',
 'MATT.CORONATO_CGY',
 'MATT.DUCHENE_DAL',
 'MATT.DUMBA_DAL',
 'MATT.GRZELCYK_PIT',
 'MATT.KIERSTED_FLA',
 'MATT.MARTIN_NYI',
 'MATT.NIETO_PIT',
 'MATT.REMPE_NYR',
 'MATT.ROY_WSH',
 'MATT.SAVOIE_EDM',
 'MATT.STIENBURG_COL',
 'MATTHEW.HIGHMORE_OTT',
 'MATTHEW.KESSEL_STL',
 'MATTHEW.KNIES_TOR',
 'MATTHEW.POITRAS_BOS',
 'MATTHEW.ROBERTSON_NYR',
 'MATTHEW.TKACHUK_FLA',
 'MATTHEW.WOOD_NSH',
 'MATTIAS.EKHOLM_EDM',
 'MATTIAS.JANMARK_EDM',
 'MATTIAS.SAMUELSSON_BUF',
 'MATTY.BENIERS_SEA',
 'MATVEI.MICHKOV_PHI',
 'MAVERIC.LAMOUREUX_UTA',
 'MAVRIK.BOURQUE_DAL',
 'MAX.DOMI_TOR',
 'MAX.JONES_BOS',
 'MAX.JONES_EDM',
 'MAX.PACIORETTY_TOR',
 'MAX.SASSON_VAN',
 'MAXIM.TSYPLAKOV_NYI',
 'MAXWELL.CROZIER_TBL',
 'MICHAEL.AMADIO_OTT',
 'MICHAEL.BUNTING_NSH',
 'MICHAEL.BUNTING_PIT',
 'MICHAEL.CALLAHAN_BOS',
 'MICHAEL.CARCONE_UTA',
 'MICHAEL.EYSSIMONT_SEA',
 'MICHAEL.EYSSIMONT_TBL',
 'MICHAEL.KESSELRING_UTA',
 'MICHAEL.MCCARRON_NSH',
 'MICHAEL.MILNE_MIN',
 'MICHAEL.PEZZETTA_MTL',
 'MICHAEL.RASMUSSEN_DET',
 'MICHAEL.SGARBOSSA_WSH',
 'MIKA.ZIBANEJAD_NYR',
 'MIKAEL.BACKLUND_CGY',
 'MIKAEL.GRANLUND_DAL',
 'MIKAEL.GRANLUND_SJS',
 'MIKAEL.PYYHTIA_CBJ',
 'MIKE.HARDMAN_NJD',
 'MIKE.MATHESON_MTL',
 'MIKE.REILLY_NYI',
 'MIKEY.ANDERSON_LAK',
 'MIKHAIL.SERGACHEV_UTA',
 'MIKKO.RANTANEN_CAR',
 'MIKKO.RANTANEN_COL',
 'MIKKO.RANTANEN_DAL',
 'MILES.WOOD_COL',
 'MIRO.HEISKANEN_DAL',
 'MITCH.MARNER_TOR',
 'MITCHELL.CHAFFEE_TBL',
 'MITCHELL.STEPHENS_SEA',
 'MORGAN.BARRON_WPG',
 'MORGAN.FROST_CGY',
 'MORGAN.FROST_PHI',
 'MORGAN.GEEKIE_BOS',
 'MORGAN.RIELLY_TOR',
 'MORITZ.SEIDER_DET',
 'NATE.SCHMIDT_FLA',
 'NATHAN.BASTIAN_NJD',
 'NATHAN.CLURMAN_PIT',
 'NATHAN.LEGARE_NJD',
 'NATHAN.MACKINNON_COL',
 'NATHAN.WALKER_STL',
 'NAZEM.KADRI_CGY',
 'NEAL.PIONK_WPG',
 'NIC.DOWD_WSH',
 'NICHOLAS.ROBERTSON_TOR',
 'NICK.BJUGSTAD_UTA',
 'NICK.BLANKENBURG_NSH',
 'NICK.COUSINS_OTT',
 'NICK.DESIMONE_UTA',
 'NICK.FOLIGNO_CHI',
 'NICK.JENSEN_OTT',
 'NICK.LEDDY_STL',
 'NICK.PAUL_TBL',
 'NICK.PERBIX_TBL',
 'NICK.SCHMALTZ_UTA',
 'NICK.SEELER_PHI',
 'NICK.SUZUKI_MTL',
 'NICO.HISCHIER_NJD',
 'NICO.STURM_FLA',
 'NICO.STURM_SJS',
 'NICOLAS.AUBE-KUBEL_BUF',
 'NICOLAS.AUBE-KUBEL_NYR',
 'NICOLAS.DESLAURIERS_PHI',
 'NICOLAS.HAGUE_VGK',
 'NICOLAS.ROY_VGK',
 'NIKITA.CHIBRIKOV_WPG',
 'NIKITA.GREBENKIN_TOR',
 'NIKITA.KUCHEROV_TBL',
 'NIKITA.NESTERENKO_ANA',
 'NIKITA.PRISHCHEPOV_COL',
 'NIKITA.ZADOROV_BOS',
 'NIKO.MIKKOLA_FLA',
 'NIKOLAI.KOVALENKO_COL',
 'NIKOLAI.KOVALENKO_SJS',
 'NIKOLAJ.EHLERS_WPG',
 'NIKOLAS.MATINPALO_OTT',
 'NILS.AMAN_VAN',
 'NILS.HOGLANDER_VAN',
 'NILS.LUNDKVIST_DAL',
 'NINO.NIEDERREITER_WPG',
 'NOAH.CATES_PHI',
 'NOAH.DOBSON_NYI',
 'NOAH.GREGOR_OTT',
 'NOAH.GREGOR_SJS',
 'NOAH.HANIFIN_VGK',
 'NOAH.JUULSEN_VAN',
 'NOAH.OSTLUND_BUF',
 'NOAH.PHILP_EDM',
 'NOEL.ACCIARI_PIT',
 'NOLAN.ALLAN_CHI',
 'NOLAN.FOOTE_NJD',
 'OLEN.ZELLWEGER_ANA',
 'OLIVER.BJORKSTRAND_SEA',
 'OLIVER.BJORKSTRAND_TBL',
 'OLIVER.EKMAN-LARSSON_TOR',
 'OLIVER.KAPANEN_MTL',
 'OLIVER.KYLINGTON_ANA',
 'OLIVER.KYLINGTON_COL',
 'OLIVER.MOORE_CHI',
 'OLIVER.WAHLSTROM_BOS',
 'OLIVER.WAHLSTROM_NYI',
 'OLLE.LYCKSELL_PHI',
 'OLLI.MAATTA_DET',
 'OLLI.MAATTA_UTA',
 'ONDREJ.PALAT_NJD',
 'OSKAR.BACK_DAL',
 'OSKAR.OLAUSSON_COL',
 'OSKAR.SUNDQVIST_STL',
 'OWEN.BECK_MTL',
 'OWEN.PICKERING_PIT',
 'OWEN.POWER_BUF',
 'OWEN.SILLINGER_CBJ',
 'OWEN.TIPPETT_PHI',
 'OZZY.WIESBLATT_NSH',
 'PARKER.FORD_WPG',
 'PARKER.KELLY_COL',
 'PARKER.WOTHERSPOON_BOS',
 'PATRICK.BROWN_BOS',
 'PATRICK.GILES_FLA',
 'PATRICK.GILES_SJS',
 'PATRICK.KANE_DET',
 'PATRICK.MAROON_CHI',
 'PATRIK.LAINE_MTL',
 'PAUL.COTTER_NJD',
 'PAVEL.BUCHNEVICH_STL',
 'PAVEL.DOROFEYEV_VGK',
 'PAVEL.MINTYUKOV_ANA',
 'PAVEL.ZACHA_BOS',
 'PEYTON.KREBS_BUF',
 'PHILIP.BROBERG_STL',
 'PHILIP.TOMASINO_NSH',
 'PHILIP.TOMASINO_PIT',
 'PHILIPP.KURASHEV_CHI',
 'PHILIPPE.MYERS_TOR',
 'PHILLIP.DANAULT_LAK',
 'PHILLIP.DI GIUSEPPE_VAN',
 'PIERRE-LUC.DUBOIS_WSH',
 'PIERRE-OLIVIER.JOSEPH_PIT',
 'PIERRE-OLIVIER.JOSEPH_STL',
 'PIERRE.ENGVALL_NYI',
 'PIUS.SUTER_VAN',
 'PONTUS.HOLMBERG_TOR',
 'QUINN.HUGHES_VAN',
 'QUINN.HUTSON_EDM',
 'QUINTON.BYFIELD_LAK',
 'RADEK.FAKSA_STL',
 'RADKO.GUDAS_ANA',
 'RAFAEL.HARVEY-PINARD_MTL',
 'RAPHAEL.LAVOIE_VGK',
 'RASMUS.ANDERSSON_CGY',
 'RASMUS.ASPLUND_FLA',
 'RASMUS.DAHLIN_BUF',
 'RASMUS.KUPARI_WPG',
 'RASMUS.RISTOLAINEN_PHI',
 'RASMUS.SANDIN_WSH',
 'REESE.JOHNSON_MIN',
 'REILLY.SMITH_NYR',
 'REILLY.SMITH_VGK',
 'RICKARD.RAKELL_PIT',
 'RIDLY.GREIG_OTT',
 'RILEY.DURAN_BOS',
 'RILEY.STILLMAN_CAR',
 'RILEY.TUFTE_BOS',
 'ROBBY.FABBRI_ANA',
 'ROBERT.BORTUZZO_UTA',
 'ROBERT.HAGG_VGK',
 'ROBERT.THOMAS_STL',
 'RODRIGO.ABOLS_PHI',
 'ROMAN.JOSI_NSH',
 'ROOPE.HINTZ_DAL',
 'RORY.KERINS_CGY',
 'ROSS.COLTON_COL',
 'ROSS.JOHNSTON_ANA',
 'RUTGER.MCGROARTY_PIT',
 'RYAN.DONATO_CHI',
 'RYAN.GRAVES_PIT',
 'RYAN.GREENE_CHI',
 'RYAN.HARTMAN_MIN',
 'RYAN.JOHNSON_BUF',
 'RYAN.LEONARD_WSH',
 'RYAN.LINDGREN_COL',
 'RYAN.LINDGREN_NYR',
 'RYAN.LOMBERG_CGY',
 'RYAN.MCDONAGH_TBL',
 'RYAN.MCLEOD_BUF',
 'RYAN.NUGENT-HOPKINS_EDM',
 "RYAN.O'REILLY_NSH",
 'RYAN.POEHLING_PHI',
 'RYAN.PULOCK_NYI',
 'RYAN.REAVES_TOR',
 'RYAN.SHEA_PIT',
 'RYAN.STROME_ANA',
 'RYAN.SUTER_STL',
 'RYAN.SUZUKI_CAR',
 'RYAN.UFKO_NSH',
 'RYAN.WINTERTON_SEA',
 'RYKER.EVANS_SEA',
 'SAM.BENNETT_FLA',
 'SAM.CARRICK_NYR',
 'SAM.COLANGELO_ANA',
 'SAM.LAFFERTY_BUF',
 'SAM.MALINSKI_COL',
 'SAM.MORTON_CGY',
 'SAM.POULIN_PIT',
 'SAM.REINHART_FLA',
 'SAM.RINZEL_CHI',
 'SAM.STEEL_DAL',
 'SAMUEL.BOLDUC_NYI',
 'SAMUEL.GIRARD_COL',
 'SAMUEL.HELENIUS_LAK',
 'SAMUEL.HONZEK_CGY',
 'SCOTT.LAUGHTON_PHI',
 'SCOTT.LAUGHTON_TOR',
 'SCOTT.MAYFIELD_NYI',
 'SCOTT.MORROW_CAR',
 'SCOTT.PERUNOVICH_NYI',
 'SCOTT.PERUNOVICH_STL',
 'SCOTT.SABOURIN_SJS',
 'SEAMUS.CASEY_NJD',
 'SEAN.COUTURIER_PHI',
 'SEAN.DURZI_UTA',
 'SEAN.KURALY_CBJ',
 'SEAN.MONAHAN_CBJ',
 'SEAN.WALKER_CAR',
 'SEBASTIAN.AHO_CAR',
 'SETH.JARVIS_CAR',
 'SETH.JONES_CHI',
 'SETH.JONES_FLA',
 'SHAKIR.MUKHAMADULLIN_SJS',
 'SHANE.BOWERS_NJD',
 'SHANE.PINTO_OTT',
 'SHANE.WRIGHT_SEA',
 'SHAYNE.GOSTISBEHERE_CAR',
 'SHEA.THEODORE_VGK',
 'SIDNEY.CROSBY_PIT',
 'SIMON.BENOIT_TOR',
 'SIMON.EDVINSSON_DET',
 'SIMON.HOLMSTROM_NYI',

### Skater metrics for the given time period, in this case EV xG in 2024-2025 season

In [ ]:
player_metrics

shape: (1_027, 4)
┌───────────────────────┬───────┬────────────┬────────────────┐
│ player_team           ┆ toi   ┆ metric_for ┆ metric_against │
│ ---                   ┆ ---   ┆ ---        ┆ ---            │
│ str                   ┆ i64   ┆ f64        ┆ f64            │
╞═══════════════════════╪═══════╪════════════╪════════════════╡
│ NIKITA.KUCHEROV_TBL   ┆ 77688 ┆ 67.342093  ┆ 57.792191      │
│ JONAS.RONDBJERG_VGK   ┆ 7204  ┆ 3.728668   ┆ 4.519087       │
│ FABIAN.ZETTERLUND_OTT ┆ 14848 ┆ 10.9658    ┆ 11.126272      │
│ SAM.BENNETT_FLA       ┆ 65631 ┆ 58.097245  ┆ 49.081703      │
│ JACOB.GAUCHER_PHI     ┆ 1762  ┆ 1.444801   ┆ 2.209146       │
│ …                     ┆ …     ┆ …          ┆ …              │
│ PIERRE-LUC.DUBOIS_WSH ┆ 71442 ┆ 61.654174  ┆ 48.852618      │
│ MARTIN.NECAS_COL      ┆ 29200 ┆ 29.857786  ┆ 19.199912      │
│ SAM.LAFFERTY_BUF      ┆ 33545 ┆ 16.496754  ┆ 23.334136      │
│ NIKO.MIKKOLA_FLA      ┆ 81841 ┆ 62.641544  ┆ 48.796888      │
│ MASON.APPLETON_WPG    ┆ 57754 ┆ 40.922049  ┆ 40.395344      │
└───────────────────────┴───────┴────────────┴────────────────┘

## Illustrative regression run

### Build the map of players and positions (for use in the regression training runs)

In [ ]:
position_map = build_position_map(lazy_pbp)

### Setting the parameters for the run

In [ ]:
# Time-on-ice limits for players to consider in the regression
toi_limits = dict(ev_r=1, ev_p=1, other_r=1, other_p=1)

# Metrics to loop through
metrics = ["xg", "corsi", "goals"]

# Sessions (i.e., regular season, playoffs) to loop through
sessions = ["R", "P"]

# Situations to loop through
situations = ["EV", "PP", "SH"]

### Setting the directory where the stints files are saved

In [ ]:
# Directory where the aggregated stints dataframes are stored
stints_directory = Path("./data/processed/")

### Running the regression

In [ ]:
# Running the regression for the years selected, should take 60-90 seconds per year
regression_results = run_all_regressions(
    stints_directory=stints_directory,
    position_map=position_map,
    seasons=seasons,
    sessions=sessions,
    situations=situations,
    metrics=metrics,
    toi_limits=toi_limits,
)

Output()

In [ ]:
# Filtering dataframe just to show a piece of the results
filter_conditions = (pl.col("session") == "R", pl.col("season") == 20242025, pl.col("situation") == "EV")

# Top players by offensive xG z-score in 2024-25 season
regression_results.filter(filter_conditions).sort("off_coeff_xg_z", descending=True).head(10)

shape: (10, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sea ┆ ses ┆ pla ┆ tea ┆ pos ┆ sit ┆ toi ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot │
│ son ┆ sio ┆ yer ┆ m   ┆ --- ┆ uat ┆ _mi ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ │
│ --- ┆ n   ┆ --- ┆ --- ┆ str ┆ ion ┆ nut ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap │
│ i32 ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ es  ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ _go ┆ r_x ┆ r_c ┆ r_g ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ _go ┆ r_x ┆ r_c ┆ r_g ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g │
│     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ rsi ┆ als ┆ --- ┆ rsi ┆ als ┆ g   ┆ ors ┆ oal ┆ st_ ┆ st_ ┆ st_ ┆ xg  ┆ cor ┆ goa ┆ 0_x ┆ 0_c ┆ 0_g ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g   ┆ ors ┆ oal ┆ _z  ┆ rsi ┆ als ┆ _z  ┆ rsi ┆ als ┆ g_z ┆ ors ┆ oal ┆ st_ ┆ st_ ┆ st_ ┆ xg_ ┆ cor ┆ goa ┆ 0_x ┆ 0_c ┆ 0_g ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g_z ┆ ors ┆ oal │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ --- ┆ i   ┆ s   ┆ xg  ┆ cor ┆ goa ┆ --- ┆ si  ┆ ls  ┆ g   ┆ ors ┆ oal ┆ 60_ ┆ 60_ ┆ 60_ ┆ xg  ┆ cor ┆ goa ┆ --- ┆ i   ┆ s   ┆ --- ┆ _z  ┆ _z  ┆ --- ┆ _z  ┆ _z  ┆ --- ┆ i_z ┆ s_z ┆ xg_ ┆ cor ┆ goa ┆ z   ┆ si_ ┆ ls_ ┆ g_z ┆ ors ┆ oal ┆ 60_ ┆ 60_ ┆ 60_ ┆ xg_ ┆ cor ┆ goa ┆ --- ┆ i_z ┆ s_z │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ si  ┆ ls  ┆ f64 ┆ --- ┆ --- ┆ --- ┆ i   ┆ s   ┆ xg  ┆ cor ┆ goa ┆ --- ┆ si  ┆ ls  ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ z   ┆ si_ ┆ ls_ ┆ --- ┆ z   ┆ z   ┆ --- ┆ i_z ┆ s_z ┆ xg_ ┆ cor ┆ goa ┆ z   ┆ si_ ┆ ls_ ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ si  ┆ ls  ┆ f64 ┆ --- ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆ --- ┆ z   ┆ z   ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ z   ┆ si_ ┆ ls_ ┆ --- ┆ z   ┆ z   ┆     ┆ f64 ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆ --- ┆ z   ┆ z   ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ R   ┆ LEO ┆ EDM ┆ C   ┆ EV  ┆ 122 ┆ 0.5 ┆ 3.2 ┆ 0.4 ┆ 0.0 ┆ -0. ┆ -0. ┆ 78. ┆ 137 ┆ 79. ┆ 50. ┆ 113 ┆ 47. ┆ 27. ┆ 238 ┆ 32. ┆ 3.8 ┆ 67. ┆ 3.8 ┆ 2.4 ┆ 55. ┆ 2.3 ┆ 1.3 ┆ 11. ┆ 1.5 ┆ 0.5 ┆ 3.9 ┆ 0.5 ┆ 4.1 ┆ 2.3 ┆ 3.7 ┆ 0.2 ┆ -0. ┆ -1. ┆ 2.6 ┆ 1.8 ┆ 2.5 ┆ 1.2 ┆ 1.2 ┆ 1.1 ┆ 4.6 ┆ 3.7 ┆ 3.3 ┆ 2.3 ┆ 1.4 ┆ 1.5 ┆ -0. ┆ -0. ┆ -0. ┆ 1.5 ┆ 1.2 ┆ 0.9 ┆ 3.2 ┆ 2.1 ┆ 3.9 │
│ 420 ┆     ┆ N.D ┆     ┆     ┆     ┆ 6.0 ┆ 843 ┆ 431 ┆ 607 ┆ 374 ┆ 717 ┆ 109 ┆ 289 ┆ 0.0 ┆ 0   ┆ 350 ┆ 2.0 ┆ 0   ┆ 939 ┆ .0  ┆ 0   ┆ 313 ┆ 045 ┆ 661 ┆ 640 ┆ 398 ┆ 001 ┆ 673 ┆ 647 ┆ 660 ┆ 468 ┆ 603 ┆ 703 ┆ 239 ┆ 166 ┆ 808 ┆ 239 ┆ 550 ┆ 411 ┆ 362 ┆ 065 ┆ 185 ┆ 856 ┆ 631 ┆ 570 ┆ 248 ┆ 952 ┆ 039 ┆ 971 ┆ 574 ┆ 518 ┆ 142 ┆ 385 ┆ 180 ┆ 263 ┆ 699 ┆ 979 ┆ 367 ┆ 617 ┆ 248 │
│ 25  ┆     ┆ RAI ┆     ┆     ┆     ┆ 333 ┆ 23  ┆ 85  ┆ 13  ┆ 43  ┆ 157 ┆ 602 ┆ 765 ┆     ┆     ┆ 188 ┆     ┆     ┆ 577 ┆     ┆     ┆ 69  ┆ 485 ┆ 27  ┆ 53  ┆ 168 ┆ 01  ┆ 16  ┆ 318 ┆ 26  ┆ 8   ┆ 42  ┆ 15  ┆ 67  ┆ 78  ┆ 26  ┆ 29  ┆ 304 ┆ 486 ┆ 47  ┆ 04  ┆ 87  ┆ 85  ┆ 3   ┆ 64  ┆ 16  ┆ 1   ┆ 06  ┆ 94  ┆ 44  ┆ 08  ┆ 706 ┆ 944 ┆ 9   ┆ 98  ┆ 08  ┆ 46  ┆ 39  ┆ 09  ┆ 42  │
│     ┆     ┆ SAI ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ TL  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ NAT ┆ COL ┆ C   ┆ EV  ┆ 139 ┆ 0.5 ┆ 5.2 ┆ 0.1 ┆ 0.0 ┆ -0. ┆ -0. ┆ 82. ┆ 156 ┆ 73. ┆ 61. ┆ 134 ┆ 51. ┆ 21. ┆ 218 ┆ 22. ┆ 3.5 ┆ 67. ┆ 3.1 ┆ 2.6 ┆ 57. ┆ 2.1 ┆ 0.9 ┆ 9.3 ┆ 0.9 ┆ 0.5 ┆ 5.7 ┆ 0.2 ┆ 4.0 ┆ 3.7 ┆ 1.1 ┆ 0.2 ┆ -0. ┆ -1. ┆ 2.8 ┆ 2.2 ┆ 2.2 ┆ 1.8 ┆ 1.7 ┆ 1.3 ┆ 3.5 ┆ 3.4 ┆ 2.2 ┆ 1.9 ┆ 1.4 ┆ 0.8 ┆ 0.1 ┆ -0. ┆ -0. ┆ 1.0 ┆ 1.0 ┆ 0.6 ┆ 3.1 ┆ 3.1 ┆ 1.5 │
│ 420 ┆     ┆ HAN ┆     ┆     ┆     ┆ 5.6 ┆ 738 ┆ 423 ┆ 503 ┆ 449 ┆ 537 ┆ 079 ┆ 920 ┆ 3.0 ┆ 0   ┆ 644 ┆ 5.0 ┆ 0   ┆ 276 ┆ .0  ┆ 0   ┆ 648 ┆ 196 ┆ 383 ┆ 501 ┆ 823 ┆ 925 ┆ 146 ┆ 722 ┆ 458 ┆ 288 ┆ 796 ┆ 301 ┆ 492 ┆ 244 ┆ 964 ┆ 969 ┆ 411 ┆ 052 ┆ 696 ┆ 593 ┆ 364 ┆ 885 ┆ 707 ┆ 725 ┆ 324 ┆ 787 ┆ 741 ┆ 603 ┆ 790 ┆ 571 ┆ 030 ┆ 026 ┆ 254 ┆ 864 ┆ 438 ┆ 705 ┆ 315 ┆ 435 ┆ 873 │
│ 25  ┆     ┆ .MA ┆     ┆     ┆     ┆ 166 ┆ 62  ┆ 33  ┆ 14  ┆ 93  ┆ 28  ┆ 801 ┆ 234 ┆     ┆     ┆ 183 ┆     ┆     ┆ 05  ┆     ┆     ┆ 86  ┆ 102 ┆ 98  ┆ 91  ┆ 901 ┆ 79  ┆ 95  ┆ 01  ┆ 18  ┆ 69  ┆ 13  ┆ 15  ┆ 16  ┆ 05  ┆ 41  ┆ 1   ┆ 95  ┆ 371 ┆ 55  ┆ 82  ┆ 41  ┆ 14  ┆ 63  ┆ 95  ┆ 59  ┆ 61  ┆ 84  ┆ 19  ┆ 08  ┆ 76  ┆ 79  ┆ 35  ┆ 415 ┆ 33  ┆ 88  ┆ 25  ┆ 08  ┆ 6   ┆ 76  │
│     ┆     ┆ CKI ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ NNO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ N   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ BRA ┆ OTT ┆ L   ┆ EV  ┆ 101 ┆ 0.4 ┆ 5.3 ┆ 0.0 ┆ -0. ┆ 0.1 ┆ -0. ┆ 53. ┆ 114 ┆ 43. ┆ 38. ┆ 966 ┆ 38. ┆ 14. ┆ 177 ┆ 5.0 ┆ 3.1 ┆ 67. ┆ 2.5 ┆ 2.3 ┆ 57. ┆ 2.2 ┆ 0.8 ┆ 10. ┆ 0.2 ┆ 0.5 ┆ 5.1 ┆ 0.1 ┆ 3.9 ┆ 3.9 ┆ 0.5 ┆ -1. ┆ 0.2 ┆ -1. ┆ 1.5 ┆ 1.4 ┆ 0.9 ┆ 0.8 ┆ 1.0 ┆ 0.8 ┆ 2.4 ┆ 2.7 ┆ 0.4 ┆ 1.0 ┆ 1.4 ┆ 0.2 ┆ -0. ┆ -0. ┆ -0. ┆ 1.1 ┆ 0.9 ┆ 0.3 ┆ 3.5 ┆ 2.8 ┆ 1.0 │
│ 420 ┆     ┆ DY. ┆     ┆     ┆     ┆ 4.7 ┆ 687 ┆ 288 ┆ 750 ┆ 103 ┆ 937 ┆ 081 ┆ 036 ┆ 3.0 ┆ 0   ┆ 969 ┆ .0  ┆ 0   ┆ 067 ┆ .0  ┆     ┆ 358 ┆ 580 ┆ 424 ┆ 040 ┆ 115 ┆ 467 ┆ 317 ┆ 465 ┆ 956 ┆ 725 ┆ 351 ┆ 561 ┆ 527 ┆ 988 ┆ 207 ┆ 047 ┆ 398 ┆ 058 ┆ 374 ┆ 501 ┆ 105 ┆ 756 ┆ 484 ┆ 669 ┆ 543 ┆ 104 ┆ 438 ┆ 967 ┆ 411 ┆ 767 ┆ 238 ┆ 011 ┆ 278 ┆ 273 ┆ 990 ┆ 676 ┆ 207 ┆ 897 ┆ 055 │
│ 25  ┆     ┆ TKA ┆     ┆     ┆     ┆ 833 ┆ 4   ┆ 76  ┆ 95  ┆ 767 ┆ 25  ┆ 022 ┆ 426 ┆     ┆     ┆ 094 ┆     ┆     ┆ 332 ┆     ┆     ┆ 28  ┆ 929 ┆ 15  ┆ 84  ┆ 64  ┆ 85  ┆ 44  ┆ 288 ┆ 3   ┆ 07  ┆ 5   ┆ 18  ┆ 93  ┆ 76  ┆ 82  ┆ 927 ┆ 69  ┆ 541 ┆     ┆ 37  ┆ 24  ┆ 17  ┆ 22  ┆ 65  ┆ 52  ┆ 72  ┆ 84  ┆ 71  ┆ 03  ┆ 54  ┆ 695 ┆ 987 ┆ 665 ┆ 85  ┆ 05  ┆ 44  ┆ 02  ┆ 69  ┆ 61  │
│     ┆     ┆ CHU ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ K   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ ZAC ┆ CBJ ┆ D   ┆ EV  ┆ 176 ┆ 0.4 ┆ 6.0 ┆ 0.1 ┆ 0.0 ┆ 0.8 ┆ -0. ┆ 92. ┆ 195 ┆ 91. ┆ 79. ┆ 179 ┆ 68. ┆ 12. ┆ 166 ┆ 23. ┆ 3.1 ┆ 66. ┆ 3.0 ┆ 2.7 ┆ 60. ┆ 2.3 ┆ 0.4 ┆ 5.6 ┆ 0.7 ┆ 0.4 ┆ 5.1 ┆ 0.2 ┆ 3.8 ┆ 4.0 ┆ 1.5 ┆ -0. ┆ 0.6 ┆ -1. ┆ 2.6 ┆ 2.3 ┆ 2.5 ┆ 2.1 ┆ 2.1 ┆ 1.6 ┆ 2.0 ┆ 2.3 ┆ 2.4 ┆ 1.1 ┆ 1.3 ┆ 0.8 ┆ 0.3 ┆ 0.5 ┆ -0. ┆ 0.6 ┆ 0.6 ┆ 0.6 ┆ 2.8 ┆ 2.6 ┆ 2.0 │
│ 420 ┆     ┆ H.W ┆     ┆     ┆     ┆ 5.8 ┆ 678 ┆ 162 ┆ 502 ┆ 060 ┆ 546 ┆ 121 ┆ 467 ┆ 9.0 ┆ 0   ┆ 637 ┆ 3.0 ┆ 0   ┆ 830 ┆ .0  ┆ 0   ┆ 418 ┆ 562 ┆ 919 ┆ 058 ┆ 921 ┆ 104 ┆ 359 ┆ 402 ┆ 814 ┆ 617 ┆ 615 ┆ 718 ┆ 025 ┆ 164 ┆ 501 ┆ 003 ┆ 774 ┆ 330 ┆ 169 ┆ 786 ┆ 610 ┆ 781 ┆ 118 ┆ 942 ┆ 153 ┆ 326 ┆ 386 ┆ 641 ┆ 438 ┆ 295 ┆ 838 ┆ 100 ┆ 192 ┆ 403 ┆ 310 ┆ 141 ┆ 385 ┆ 777 ┆ 849 │
│ 25  ┆     ┆ ERE ┆     ┆     ┆     ┆ 666 ┆ 24  ┆ 23  ┆ 46  ┆ 99  ┆ 79  ┆ 615 ┆ 339 ┆     ┆     ┆ 238 ┆     ┆     ┆ 101 ┆     ┆     ┆ 23  ┆ 217 ┆ 66  ┆ 86  ┆ 927 ┆ 8   ┆ 37  ┆ 9   ┆ 86  ┆ 25  ┆ 44  ┆ 61  ┆ 75  ┆ 01  ┆ 42  ┆ 21  ┆ 1   ┆ 779 ┆ 44  ┆ 99  ┆ 5   ┆ 48  ┆ 92  ┆ 12  ┆ 98  ┆ 38  ┆ 94  ┆ 3   ┆ 46  ┆ 39  ┆ 11  ┆ 29  ┆ 526 ┆ 52  ┆ 65  ┆ 83  ┆ 15  ┆ 14  ┆ 78  │
│     ┆     ┆ NSK ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ I   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ CON ┆ EDM ┆ C   ┆ EV  ┆ 119 ┆ 0.5 ┆ 2.1 ┆ 0.4 ┆ -0. ┆ -1. ┆ 0.1 ┆ 77. ┆ 130 ┆ 80. ┆ 47. ┆ 107 ┆ 58. ┆ 29. ┆ 227 ┆ 22. ┆ 3.9 ┆ 65. ┆ 4.0 ┆ 2.4 ┆ 54. ┆ 2.9 ┆ 1.5 ┆ 11. ┆ 1.1 ┆ 0.5 ┆ 3.7 ┆ 0.3 ┆ 3.7 ┆ 1.5 ┆ 3.6 ┆ -0. ┆ -1. ┆ 1.3 ┆ 2.6 ┆ 1.6 ┆ 2.5 ┆ 1.1 ┆ 1.1 ┆ 1.7 ┆ 4.9 ┆ 3.6 ┆ 2.2 ┆ 2.5 ┆ 1.2 ┆ 1.7 ┆ -0. ┆ -0. ┆ 0.2 ┆ 1.6 ┆ 1.2 ┆ 0.7 ┆ 3.2 ┆ 2.0 ┆ 2.2 │
│ 420 ┆     ┆ NOR ┆     ┆     ┆     ┆ 3.6 ┆ 275 ┆ 659 ┆ 458 ┆ 016 ┆ 557 ┆ 226 ┆ 902 ┆ 5.0 ┆ 0   ┆ 969 ┆ 8.0 ┆ 0   ┆ 933 ┆ .0  ┆ 0   ┆ 160 ┆ 599 ┆ 214 ┆ 113 ┆ 189 ┆ 155 ┆ 047 ┆ 410 ┆ 058 ┆ 442 ┆ 236 ┆ 232 ┆ 182 ┆ 581 ┆ 572 ┆ 299 ┆ 196 ┆ 867 ┆ 167 ┆ 539 ┆ 656 ┆ 585 ┆ 344 ┆ 497 ┆ 516 ┆ 211 ┆ 741 ┆ 359 ┆ 504 ┆ 000 ┆ 212 ┆ 565 ┆ 398 ┆ 599 ┆ 464 ┆ 550 ┆ 211 ┆ 339 ┆ 274 │
│ 25  ┆     ┆ .MC ┆     ┆     ┆     ┆     ┆ 46  ┆ 32  ┆ 72  ┆ 668 ┆ 722 ┆ 05  ┆ 676 ┆     ┆     ┆ 066 ┆     ┆     ┆ 61  ┆     ┆     ┆ 19  ┆ 866 ┆ 48  ┆ 14  ┆ 008 ┆ 5   ┆ 06  ┆ 858 ┆ 98  ┆ 14  ┆ 55  ┆ 67  ┆ 71  ┆ 16  ┆ 66  ┆ 162 ┆ 837 ┆ 01  ┆ 35  ┆ 8   ┆ 12  ┆ 91  ┆ 35  ┆ 72  ┆ 99  ┆ 63  ┆ 84  ┆ 7   ┆ 66  ┆ 65  ┆ 346 ┆ 192 ┆ 93  ┆ 47  ┆ 17  ┆ 34  ┆ 66  ┆ 7   ┆ 1   │
│     ┆     ┆ DAV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ID  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ MAT ┆ FLA ┆ L   ┆ EV  ┆ 738 ┆ 0.4 ┆ 2.8 ┆ 0.2 ┆ -0. ┆ -1. ┆ 0.0 ┆ 43. ┆ 805 ┆ 40. ┆ 29. ┆ 684 ┆ 31. ┆ 14. ┆ 121 ┆ 9.0 ┆ 3.5 ┆ 65. ┆ 3.2 ┆ 2.3 ┆ 55. ┆ 2.5 ┆ 1.1 ┆ 9.8 ┆ 0.7 ┆ 0.4 ┆ 4.5 ┆ 0.1 ┆ 3.4 ┆ 2.0 ┆ 1.6 ┆ -0. ┆ -1. ┆ 0.4 ┆ 1.0 ┆ 0.6 ┆ 0.7 ┆ 0.3 ┆ 0.3 ┆ 0.4 ┆ 2.4 ┆ 1.8 ┆ 0.8 ┆ 1.6 ┆ 1.1 ┆ 0.8 ┆ -0. ┆ -0. ┆ -0. ┆ 1.5 ┆ 0.9 ┆ 0.6 ┆ 2.7 ┆ 2.5 ┆ 1.0 │
│ 420 ┆     ┆ THE ┆     ┆     ┆     ┆ .56 ┆ 129 ┆ 455 ┆ 033 ┆ 044 ┆ 667 ┆ 428 ┆ 405 ┆ .0  ┆ 0   ┆ 355 ┆ .0  ┆ 0   ┆ 049 ┆ .0  ┆     ┆ 261 ┆ 396 ┆ 495 ┆ 847 ┆ 567 ┆ 183 ┆ 413 ┆ 298 ┆ 311 ┆ 570 ┆ 130 ┆ 604 ┆ 584 ┆ 964 ┆ 672 ┆ 462 ┆ 281 ┆ 605 ┆ 228 ┆ 157 ┆ 653 ┆ 202 ┆ 343 ┆ 521 ┆ 512 ┆ 350 ┆ 678 ┆ 426 ┆ 705 ┆ 966 ┆ 102 ┆ 188 ┆ 027 ┆ 044 ┆ 449 ┆ 268 ┆ 858 ┆ 248 ┆ 355 │
│ 25  ┆     ┆ W.T ┆     ┆     ┆     ┆ 666 ┆ 27  ┆ 61  ┆ 27  ┆ 147 ┆ 457 ┆ 96  ┆ 293 ┆     ┆     ┆ 334 ┆     ┆     ┆ 959 ┆     ┆     ┆ 78  ┆ 94  ┆ 37  ┆ 81  ┆ 089 ┆ 91  ┆ 97  ┆ 51  ┆ 46  ┆ 74  ┆ 18  ┆ 31  ┆ 36  ┆ 59  ┆ 8   ┆ 96  ┆ 807 ┆ 51  ┆ 01  ┆ 48  ┆ 72  ┆ 63  ┆ 44  ┆ 85  ┆ 2   ┆ 86  ┆ 92  ┆ 81  ┆ 51  ┆ 39  ┆ 757 ┆ 039 ┆ 969 ┆ 04  ┆ 26  ┆ 92  ┆ 94  ┆ 43  ┆ 56  │
│     ┆     ┆ KAC ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ HUK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ ADA ┆ NYR ┆ D   ┆ EV  ┆ 129 ┆ 0.4 ┆ 2.6 ┆ 0.2 ┆ -0. ┆ -2. ┆ -0. ┆ 65. ┆ 134 ┆ 70. ┆ 54. ┆ 121 ┆ 53. ┆ 11. ┆ 126 ┆ 17. ┆ 3.0 ┆ 62. ┆ 3.2 ┆ 2.5 ┆ 56. ┆ 2.4 ┆ 0.5 ┆ 5.8 ┆ 0.7 ┆ 0.5 ┆ 5.5 ┆ 0.3 ┆ 3.3 ┆ 1.8 ┆ 2.6 ┆ -1. ┆ -2. ┆ -0. ┆ 1.4 ┆ 1.2 ┆ 1.6 ┆ 1.0 ┆ 0.9 ┆ 1.0 ┆ 1.7 ┆ 1.7 ┆ 1.8 ┆ 0.9 ┆ 0.7 ┆ 0.9 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.7 ┆ 0.6 ┆ 0.6 ┆ 3.5 ┆ 2.8 ┆ 2.6 │
│ 420 ┆     ┆ M.F ┆     ┆     ┆     ┆ 7.8 ┆ 110 ┆ 474 ┆ 548 ┆ 167 ┆ 913 ┆ 088 ┆ 276 ┆ 5.0 ┆ 0   ┆ 273 ┆ 9.0 ┆ 0   ┆ 002 ┆ .0  ┆ 0   ┆ 176 ┆ 178 ┆ 360 ┆ 090 ┆ 353 ┆ 501 ┆ 086 ┆ 248 ┆ 858 ┆ 788 ┆ 612 ┆ 432 ┆ 395 ┆ 179 ┆ 332 ┆ 610 ┆ 064 ┆ 980 ┆ 591 ┆ 040 ┆ 767 ┆ 406 ┆ 859 ┆ 190 ┆ 296 ┆ 731 ┆ 075 ┆ 593 ┆ 000 ┆ 824 ┆ 038 ┆ 201 ┆ 093 ┆ 321 ┆ 508 ┆ 167 ┆ 509 ┆ 825 ┆ 234 │
│ 25  ┆     ┆ OX  ┆     ┆     ┆     ┆ 833 ┆ 42  ┆ 25  ┆ 98  ┆ 824 ┆ 788 ┆ 333 ┆ 146 ┆     ┆     ┆ 618 ┆     ┆     ┆ 528 ┆     ┆     ┆ 59  ┆ 162 ┆ 38  ┆ 21  ┆ 293 ┆ 43  ┆ 37  ┆ 69  ┆ 95  ┆ 66  ┆ 13  ┆ 31  ┆ 84  ┆ 43  ┆ 03  ┆ 268 ┆ 349 ┆ 845 ┆ 55  ┆ 41  ┆ 78  ┆ 97  ┆ 06  ┆ 24  ┆ 58  ┆ 43  ┆ 1   ┆ 98  ┆ 75  ┆ 88  ┆ 03  ┆ 808 ┆ 136 ┆ 42  ┆ 81  ┆ 57  ┆ 82  ┆ 98  ┆ 47  │
│     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ SEB ┆ CAR ┆ R   ┆ EV  ┆ 111 ┆ 0.3 ┆ 3.8 ┆ 0.1 ┆ 0.0 ┆ -1. ┆ 0.1 ┆ 62. ┆ 123 ┆ 56. ┆ 47. ┆ 106 ┆ 60. ┆ 15. ┆ 177 ┆ -4. ┆ 3.3 ┆ 66. ┆ 3.0 ┆ 2.5 ┆ 57. ┆ 3.2 ┆ 0.8 ┆ 9.5 ┆ -0. ┆ 0.3 ┆ 5.0 ┆ -0. ┆ 3.2 ┆ 2.8 ┆ 1.7 ┆ 0.0 ┆ -1. ┆ 2.0 ┆ 2.0 ┆ 1.6 ┆ 1.6 ┆ 1.3 ┆ 1.3 ┆ 2.0 ┆ 3.2 ┆ 3.1 ┆ -0. ┆ 1.7 ┆ 1.4 ┆ 0.8 ┆ -0. ┆ -0. ┆ 0.5 ┆ 1.0 ┆ 1.1 ┆ 0.1 ┆ 2.2 ┆ 3.0 ┆ -0. │
│ 420 ┆     ┆ AST ┆     ┆     ┆     ┆ 4.5 ┆ 719 ┆ 425 ┆ 831 ┆ 139 ┆ 213 ┆ 899 ┆ 846 ┆ 7.0 ┆ 0   ┆ 024 ┆ 0.0 ┆ 0   ┆ 821 ┆ .0  ┆ 0   ┆ 831 ┆ 590 ┆ 146 ┆ 314 ┆ 062 ┆ 299 ┆ 517 ┆ 283 ┆ 215 ┆ 580 ┆ 558 ┆ 006 ┆ 085 ┆ 860 ┆ 232 ┆ 902 ┆ 122 ┆ 780 ┆ 603 ┆ 868 ┆ 324 ┆ 587 ┆ 208 ┆ 148 ┆ 638 ┆ 675 ┆ 460 ┆ 318 ┆ 444 ┆ 304 ┆ 024 ┆ 157 ┆ 695 ┆ 991 ┆ 742 ┆ 257 ┆ 818 ┆ 601 ┆ 058 │
│ 25  ┆     ┆ IAN ┆     ┆     ┆     ┆ 666 ┆ 83  ┆ 05  ┆ 67  ┆ 19  ┆ 378 ┆ 07  ┆ 166 ┆     ┆     ┆ 477 ┆     ┆     ┆ 688 ┆     ┆     ┆ 71  ┆ 902 ┆ 25  ┆ 49  ┆ 536 ┆ 55  ┆ 22  ┆ 67  ┆ 33  ┆ 64  ┆ 83  ┆ 74  ┆ 69  ┆ 52  ┆ 48  ┆ 91  ┆ 659 ┆ 66  ┆ 66  ┆ 13  ┆ 34  ┆ 51  ┆ 95  ┆ 97  ┆ 4   ┆ 23  ┆ 984 ┆ 36  ┆ 43  ┆ 03  ┆ 257 ┆ 747 ┆ 73  ┆ 69  ┆ 77  ┆ 16  ┆     ┆ 03  ┆ 728 │
│     ┆     ┆ .AH ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ O   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ MAR ┆ PIT ┆ D   ┆ EV  ┆ 887 ┆ 0.3 ┆ 2.8 ┆ 0.2 ┆ 0.0 ┆ 1.9 ┆ 0.1 ┆ 48. ┆ 956 ┆ 47. ┆ 42. ┆ 953 ┆ 51. ┆ 6.3 ┆ 3.0 ┆ -4. ┆ 3.2 ┆ 64. ┆ 3.1 ┆ 2.8 ┆ 64. ┆ 3.4 ┆ 0.4 ┆ 0.2 ┆ -0. ┆ 0.3 ┆ 0.9 ┆ 0.0 ┆ 3.1 ┆ 1.9 ┆ 2.1 ┆ 0.7 ┆ 1.4 ┆ 1.7 ┆ 0.7 ┆ 0.4 ┆ 0.7 ┆ 0.5 ┆ 0.4 ┆ 0.9 ┆ 0.9 ┆ 0.0 ┆ -0. ┆ 1.4 ┆ 1.0 ┆ 0.9 ┆ 0.6 ┆ 1.0 ┆ 0.6 ┆ 0.6 ┆ 0.0 ┆ -0. ┆ 1.8 ┆ 0.5 ┆ 0.3 │

## Analyzing the RAPM model

### Load data

In [ ]:
parquet_file = Path("./data/results/results.parquet")

rapm_results = pl.read_parquet(parquet_file)

### Previewing the results

In [ ]:
# Filtering dataframe just to show a piece of the results
filter_conditions = (pl.col("session") == "R", pl.col("situation") == "EV")

# Top regular season, even strength defensive players, all-time
rapm_results.filter(filter_conditions).sort(pl.col("def_coeff_xg_z"), descending=False).head(10)

shape: (10, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sea ┆ ses ┆ pla ┆ tea ┆ pos ┆ sit ┆ toi ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot │
│ son ┆ sio ┆ yer ┆ m   ┆ --- ┆ uat ┆ _mi ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ │
│ --- ┆ n   ┆ --- ┆ --- ┆ str ┆ ion ┆ nut ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap │
│ i32 ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ es  ┆ _go ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ r_g ┆ r_x ┆ r_c ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g ┆ _go ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ r_g ┆ r_x ┆ r_c ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g │
│     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ als ┆ --- ┆ rsi ┆ als ┆ --- ┆ rsi ┆ oal ┆ g   ┆ ors ┆ st_ ┆ st_ ┆ st_ ┆ goa ┆ xg  ┆ cor ┆ 0_g ┆ 0_x ┆ 0_c ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g   ┆ ors ┆ oal ┆ als ┆ _z  ┆ rsi ┆ als ┆ _z  ┆ rsi ┆ oal ┆ g_z ┆ ors ┆ st_ ┆ st_ ┆ st_ ┆ goa ┆ xg_ ┆ cor ┆ 0_g ┆ 0_x ┆ 0_c ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g_z ┆ ors ┆ oal │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ s   ┆ --- ┆ i   ┆ goa ┆ xg  ┆ cor ┆ ls  ┆ --- ┆ si  ┆ oal ┆ g   ┆ ors ┆ 60_ ┆ 60_ ┆ 60_ ┆ goa ┆ xg  ┆ cor ┆ --- ┆ i   ┆ s   ┆ _z  ┆ --- ┆ _z  ┆ _z  ┆ --- ┆ _z  ┆ s_z ┆ --- ┆ i_z ┆ goa ┆ xg_ ┆ cor ┆ ls_ ┆ z   ┆ si_ ┆ oal ┆ g_z ┆ ors ┆ 60_ ┆ 60_ ┆ 60_ ┆ goa ┆ xg_ ┆ cor ┆ --- ┆ i_z ┆ s_z │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ ls  ┆ --- ┆ si  ┆ --- ┆ f64 ┆ --- ┆ s   ┆ --- ┆ i   ┆ goa ┆ xg  ┆ cor ┆ ls  ┆ --- ┆ si  ┆ f64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ ls_ ┆ z   ┆ si_ ┆ z   ┆ --- ┆ z   ┆ s_z ┆ --- ┆ i_z ┆ goa ┆ xg_ ┆ cor ┆ ls_ ┆ z   ┆ si_ ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ ls  ┆ --- ┆ si  ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ z   ┆ --- ┆ z   ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ ls_ ┆ z   ┆ si_ ┆ z   ┆ --- ┆ z   ┆     ┆ f64 ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ z   ┆ --- ┆ z   ┆ --- ┆ f64 ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ R   ┆ CHR ┆ CGY ┆ D   ┆ EV  ┆ 100 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -5. ┆ 39. ┆ 41. ┆ 898 ┆ 26. ┆ 27. ┆ 731 ┆ 13. ┆ 13. ┆ 167 ┆ 2.3 ┆ 2.4 ┆ 53. ┆ 1.5 ┆ 1.6 ┆ 43. ┆ 0.7 ┆ 0.8 ┆ 9.9 ┆ 0.4 ┆ 5.6 ┆ 0.3 ┆ -0. ┆ 0.8 ┆ 0.1 ┆ -3. ┆ -3. ┆ -4. ┆ 1.1 ┆ 1.4 ┆ 1.3 ┆ 0.3 ┆ 0.5 ┆ 0.8 ┆ 1.6 ┆ 2.9 ┆ 3.5 ┆ 0.0 ┆ 0.4 ┆ 0.2 ┆ -0. ┆ -1. ┆ -1. ┆ 0.6 ┆ 1.0 ┆ 1.2 ┆ 3.3 ┆ 3.6 ┆ 1.8 │
│ 020 ┆     ┆ IS. ┆     ┆     ┆     ┆ 7.0 ┆ 059 ┆ 720 ┆ 830 ┆ 366 ┆ 363 ┆ 579 ┆ 0   ┆ 172 ┆ .0  ┆ 0   ┆ 712 ┆ .0  ┆ 0   ┆ 459 ┆ .0  ┆ 236 ┆ 531 ┆ 504 ┆ 491 ┆ 511 ┆ 554 ┆ 745 ┆ 019 ┆ 501 ┆ 352 ┆ 626 ┆ 073 ┆ 523 ┆ 204 ┆ 228 ┆ 360 ┆ 743 ┆ 559 ┆ 126 ┆ 844 ┆ 859 ┆ 537 ┆ 814 ┆ 854 ┆ 177 ┆ 901 ┆ 451 ┆ 280 ┆ 247 ┆ 408 ┆ 668 ┆ 187 ┆ 451 ┆ 051 ┆ 366 ┆ 287 ┆ 749 ┆ 537 ┆ 736 │
│ 21  ┆     ┆ TAN ┆     ┆     ┆     ┆ 166 ┆ 216 ┆ 02  ┆ 65  ┆ 596 ┆ 259 ┆ 549 ┆     ┆ 539 ┆     ┆     ┆ 755 ┆     ┆     ┆ 784 ┆     ┆ 95  ┆ 39  ┆ 576 ┆ 3   ┆ 8   ┆ 393 ┆ 65  ┆ 6   ┆ 83  ┆ 61  ┆ 14  ┆ 8   ┆ 107 ┆ 93  ┆ 73  ┆ 254 ┆ 327 ┆ 412 ┆ 17  ┆ 79  ┆ 63  ┆ 66  ┆ 32  ┆ 58  ┆ 04  ┆ 58  ┆ 24  ┆ 78  ┆ 92  ┆ 9   ┆ 762 ┆ 375 ┆ 515 ┆ 42  ┆ 31  ┆ 3   ┆ 94  ┆ 65  ┆ 77  │
│     ┆     ┆ EV  ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ PAV ┆ DET ┆ C   ┆ EV  ┆ 106 ┆ 0.0 ┆ 0.3 ┆ 2.7 ┆ -0. ┆ -0. ┆ -4. ┆ 39. ┆ 48. ┆ 966 ┆ 32. ┆ 33. ┆ 850 ┆ 7.0 ┆ 14. ┆ 116 ┆ 2.1 ┆ 2.7 ┆ 54. ┆ 1.7 ┆ 1.8 ┆ 47. ┆ 0.3 ┆ 0.8 ┆ 6.5 ┆ 0.7 ┆ 6.9 ┆ 0.1 ┆ 0.3 ┆ 2.4 ┆ 1.9 ┆ -1. ┆ -3. ┆ -3. ┆ 0.8 ┆ 1.4 ┆ 1.0 ┆ 0.5 ┆ 0.6 ┆ 0.7 ┆ 0.7 ┆ 3.1 ┆ 1.9 ┆ 0.1 ┆ 0.9 ┆ 0.3 ┆ -0. ┆ -0. ┆ -0. ┆ 0.2 ┆ 1.2 ┆ 0.9 ┆ 4.3 ┆ 4.0 ┆ 1.3 │
│ 520 ┆     ┆ EL. ┆     ┆     ┆     ┆ 8.2 ┆ 507 ┆ 809 ┆ 716 ┆ 135 ┆ 397 ┆ 129 ┆ 0   ┆ 644 ┆ .0  ┆ 0   ┆ 711 ┆ .0  ┆     ┆ 933 ┆ .0  ┆ 904 ┆ 321 ┆ 255 ┆ 972 ┆ 933 ┆ 740 ┆ 931 ┆ 387 ┆ 151 ┆ 780 ┆ 006 ┆ 864 ┆ 613 ┆ 799 ┆ 014 ┆ 626 ┆ 692 ┆ 534 ┆ 485 ┆ 132 ┆ 469 ┆ 790 ┆ 238 ┆ 802 ┆ 626 ┆ 047 ┆ 953 ┆ 081 ┆ 719 ┆ 026 ┆ 294 ┆ 703 ┆ 847 ┆ 442 ┆ 457 ┆ 130 ┆ 729 ┆ 141 ┆ 231 │
│ 16  ┆     ┆ DAT ┆     ┆     ┆     ┆ 833 ┆ 15  ┆ 92  ┆ 84  ┆ 756 ┆ 038 ┆ 011 ┆     ┆ 313 ┆     ┆     ┆ 129 ┆     ┆     ┆ 184 ┆     ┆ 3   ┆ 02  ┆ 269 ┆ 76  ┆ 81  ┆ 144 ┆ 54  ┆ 2   ┆ 26  ┆ 3   ┆ 95  ┆ 72  ┆ 31  ┆ 33  ┆ 52  ┆ 313 ┆ 033 ┆ 543 ┆ 08  ┆ 68  ┆ 28  ┆ 12  ┆ 75  ┆ 69  ┆ 77  ┆ 95  ┆ 22  ┆ 66  ┆ 36  ┆ 07  ┆ 424 ┆ 785 ┆ 993 ┆ 33  ┆ 92  ┆ 99  ┆ 71  ┆ 82  ┆ 48  │
│     ┆     ┆ SYU ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ K   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ MIK ┆ MIN ┆ C   ┆ EV  ┆ 110 ┆ -0. ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ -4. ┆ 40. ┆ 42. ┆ 100 ┆ 38. ┆ 30. ┆ 919 ┆ 2.0 ┆ 12. ┆ 83. ┆ 2.1 ┆ 2.3 ┆ 54. ┆ 2.0 ┆ 1.6 ┆ 49. ┆ 0.1 ┆ 0.6 ┆ 4.5 ┆ 0.2 ┆ 3.0 ┆ -0. ┆ -1. ┆ -0. ┆ -1. ┆ -1. ┆ -3. ┆ -3. ┆ 0.6 ┆ 0.9 ┆ 0.9 ┆ 0.6 ┆ 0.2 ┆ 0.8 ┆ 0.1 ┆ 2.7 ┆ 1.3 ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ -1. ┆ -1. ┆ 0.1 ┆ 1.2 ┆ 0.6 ┆ 1.7 ┆ 1.7 ┆ -0. │
│ 720 ┆     ┆ KO. ┆     ┆     ┆     ┆ 5.5 ┆ 154 ┆ 092 ┆ 700 ┆ 146 ┆ 325 ┆ 729 ┆ 0   ┆ 913 ┆ 2.0 ┆ 0   ┆ 061 ┆ .0  ┆     ┆ 851 ┆ 0   ┆ 708 ┆ 290 ┆ 380 ┆ 623 ┆ 315 ┆ 876 ┆ 085 ┆ 975 ┆ 046 ┆ 335 ┆ 283 ┆ 008 ┆ 033 ┆ 841 ┆ 245 ┆ 302 ┆ 575 ┆ 768 ┆ 991 ┆ 367 ┆ 821 ┆ 967 ┆ 799 ┆ 027 ┆ 865 ┆ 119 ┆ 961 ┆ 021 ┆ 219 ┆ 142 ┆ 293 ┆ 576 ┆ 106 ┆ 651 ┆ 642 ┆ 311 ┆ 042 ┆ 675 ┆ 068 │
│ 18  ┆     ┆ KOI ┆     ┆     ┆     ┆ 333 ┆ 724 ┆ 337 ┆ 992 ┆ 231 ┆ 874 ┆ 377 ┆     ┆ 629 ┆     ┆     ┆ 758 ┆     ┆     ┆ 871 ┆     ┆ 98  ┆ 28  ┆ 993 ┆ 53  ┆ 25  ┆ 379 ┆ 45  ┆ 02  ┆ 13  ┆ 37  ┆ 84  ┆ 492 ┆ 155 ┆ 742 ┆ 865 ┆ 721 ┆ 285 ┆ 489 ┆ 72  ┆ 31  ┆ 66  ┆ 26  ┆ 94  ┆ 26  ┆ 11  ┆ 27  ┆ 61  ┆ 222 ┆ 1   ┆ 069 ┆ 831 ┆ 979 ┆ 719 ┆ 84  ┆ 04  ┆ 78  ┆ 54  ┆ 16  ┆ 398 │
│     ┆     ┆ VU  ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ ZAC ┆ PIT ┆ C   ┆ EV  ┆ 688 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -1. ┆ 22. ┆ 23. ┆ 575 ┆ 17. ┆ 17. ┆ 545 ┆ 5.0 ┆ 5.9 ┆ 30. ┆ 1.9 ┆ 2.0 ┆ 50. ┆ 1.4 ┆ 1.5 ┆ 47. ┆ 0.4 ┆ 0.5 ┆ 2.6 ┆ 0.3 ┆ 1.4 ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ -2. ┆ -3. ┆ -2. ┆ 0.0 ┆ 0.1 ┆ 0.2 ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.5 ┆ 1.4 ┆ 0.6 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -1. ┆ -1. ┆ 0.3 ┆ 0.8 ┆ 0.4 ┆ 2.4 ┆ 1.2 ┆ 0.7 │
│ 920 ┆     ┆ H.A ┆     ┆     ┆     ┆ .88 ┆ 085 ┆ 113 ┆ 463 ┆ 195 ┆ 304 ┆ 947 ┆ 0   ┆ 154 ┆ .0  ┆ 0   ┆ 226 ┆ .0  ┆     ┆ 273 ┆ 0   ┆ 161 ┆ 166 ┆ 081 ┆ 806 ┆ 004 ┆ 468 ┆ 354 ┆ 162 ┆ 129 ┆ 154 ┆ 839 ┆ 098 ┆ 794 ┆ 006 ┆ 407 ┆ 168 ┆ 554 ┆ 137 ┆ 235 ┆ 578 ┆ 858 ┆ 285 ┆ 232 ┆ 976 ┆ 834 ┆ 926 ┆ 991 ┆ 285 ┆ 452 ┆ 673 ┆ 755 ┆ 729 ┆ 273 ┆ 741 ┆ 614 ┆ 412 ┆ 265 ┆ 090 ┆ 850 │
│ 20  ┆     ┆ STO ┆     ┆     ┆     ┆ 333 ┆ 907 ┆ 19  ┆ 139 ┆ 787 ┆ 132 ┆ 085 ┆     ┆ 253 ┆     ┆     ┆ 876 ┆     ┆     ┆ 77  ┆     ┆ 44  ┆ 77  ┆ 049 ┆ 57  ┆ 17  ┆ 125 ┆ 87  ┆ 6   ┆ 24  ┆ 51  ┆ 46  ┆ 8   ┆ 391 ┆ 208 ┆ 306 ┆ 36  ┆ 963 ┆ 178 ┆ 84  ┆ 91  ┆ 48  ┆ 191 ┆ 835 ┆ 34  ┆ 34  ┆ 15  ┆ 55  ┆ 886 ┆ 531 ┆ 373 ┆ 559 ┆ 409 ┆ 155 ┆ 57  ┆ 76  ┆ 92  ┆ 74  ┆ 34  ┆ 79  │
│     ┆     ┆ N-R ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ EES ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ E   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ JUS ┆ DET ┆ L   ┆ EV  ┆ 977 ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -3. ┆ 40. ┆ 37. ┆ 780 ┆ 31. ┆ 27. ┆ 752 ┆ 9.0 ┆ 9.7 ┆ 28. ┆ 2.4 ┆ 2.2 ┆ 47. ┆ 1.9 ┆ 1.6 ┆ 46. ┆ 0.5 ┆ 0.5 ┆ 1.7 ┆ 0.3 ┆ 1.4 ┆ 0.1 ┆ 0.7 ┆ 0.3 ┆ -1. ┆ -1. ┆ -3. ┆ -2. ┆ 1.1 ┆ 1.0 ┆ 0.8 ┆ 0.6 ┆ 0.4 ┆ 0.7 ┆ 1.1 ┆ 1.9 ┆ 0.5 ┆ 0.5 ┆ 0.2 ┆ -0. ┆ -0. ┆ -0. ┆ -1. ┆ 0.5 ┆ 0.9 ┆ 0.2 ┆ 2.6 ┆ 0.8 ┆ 1.3 │
│ 420 ┆     ┆ TIN ┆     ┆     ┆     ┆ .76 ┆ 601 ┆ 472 ┆ 563 ┆ 062 ┆ 313 ┆ 048 ┆ 0   ┆ 027 ┆ .0  ┆ 0   ┆ 301 ┆ .0  ┆     ┆ 259 ┆ 0   ┆ 545 ┆ 721 ┆ 864 ┆ 022 ┆ 753 ┆ 145 ┆ 522 ┆ 968 ┆ 182 ┆ 610 ┆ 847 ┆ 228 ┆ 432 ┆ 898 ┆ 105 ┆ 216 ┆ 511 ┆ 529 ┆ 030 ┆ 507 ┆ 021 ┆ 836 ┆ 583 ┆ 314 ┆ 172 ┆ 537 ┆ 357 ┆ 130 ┆ 883 ┆ 649 ┆ 240 ┆ 967 ┆ 019 ┆ 044 ┆ 325 ┆ 287 ┆ 767 ┆ 691 ┆ 239 │
│ 15  ┆     ┆ .AB ┆     ┆     ┆     ┆ 666 ┆ 34  ┆ 85  ┆ 983 ┆ 738 ┆ 783 ┆ 697 ┆     ┆ 031 ┆     ┆     ┆ 037 ┆     ┆     ┆ 94  ┆     ┆ 73  ┆ 39  ┆ 18  ┆ 94  ┆ 1   ┆ 979 ┆ 79  ┆ 29  ┆ 01  ┆ 68  ┆ 13  ┆ 72  ┆ 83  ┆ 09  ┆ 5   ┆ 323 ┆ 5   ┆ 366 ┆ 63  ┆ 61  ┆ 48  ┆ 56  ┆ 02  ┆ 29  ┆ 91  ┆ 51  ┆ 65  ┆ 2   ┆ 45  ┆ 993 ┆ 12  ┆ 186 ┆     ┆ 45  ┆ 75  ┆ 54  ┆ 88  ┆ 34  ┆ 68  │
│     ┆     ┆ DEL ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ KAD ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ER  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ CHR ┆ VAN ┆ D   ┆ EV  ┆ 118 ┆ -0. ┆ -0. ┆ 0.7 ┆ -0. ┆ -0. ┆ -4. ┆ 35. ┆ 39. ┆ 104 ┆ 43. ┆ 39. ┆ 928 ┆ -8. ┆ -0. ┆ 121 ┆ 1.7 ┆ 1.9 ┆ 52. ┆ 2.1 ┆ 2.0 ┆ 46. ┆ -0. ┆ -0. ┆ 6.1 ┆ 0.3 ┆ 4.8 ┆ -0. ┆ -1. ┆ -0. ┆ 0.6 ┆ -0. ┆ -3. ┆ -3. ┆ 0.4 ┆ 0.5 ┆ 0.8 ┆ 0.8 ┆ 0.6 ┆ 0.5 ┆ -1. ┆ -0. ┆ 1.8 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -1. ┆ -0. ┆ 0.1 ┆ 0.8 ┆ 2.0 ┆ 2.8 ┆ -0. │
│ 520 ┆     ┆ IS. ┆     ┆     ┆     ┆ 7.8 ┆ 112 ┆ 067 ┆ 623 ┆ 043 ┆ 394 ┆ 039 ┆ 0   ┆ 336 ┆ 9.0 ┆ 0   ┆ 898 ┆ .0  ┆ 0   ┆ 561 ┆ .0  ┆ 678 ┆ 869 ┆ 985 ┆ 719 ┆ 152 ┆ 873 ┆ 404 ┆ 028 ┆ 117 ┆ 264 ┆ 016 ┆ 068 ┆ 248 ┆ 658 ┆ 083 ┆ 620 ┆ 483 ┆ 033 ┆ 041 ┆ 635 ┆ 167 ┆ 246 ┆ 004 ┆ 674 ┆ 013 ┆ 085 ┆ 319 ┆ 348 ┆ 470 ┆ 048 ┆ 129 ┆ 439 ┆ 108 ┆ 108 ┆ 153 ┆ 611 ┆ 675 ┆ 529 ┆ 569 │
│ 16  ┆     ┆ TAN ┆     ┆     ┆     ┆ 666 ┆ 267 ┆ 62  ┆ 65  ┆ 427 ┆ 102 ┆ 253 ┆     ┆ 484 ┆     ┆     ┆ 426 ┆     ┆     ┆ 942 ┆     ┆ 75  ┆ 14  ┆ 745 ┆ 61  ┆ 98  ┆ 948 ┆ 086 ┆ 384 ┆ 97  ┆ 82  ┆ 18  ┆ 84  ┆ 113 ┆ 351 ┆ 73  ┆ 885 ┆ 877 ┆ 824 ┆ 19  ┆ 28  ┆ 11  ┆ 3   ┆ 83  ┆ 01  ┆ 656 ┆ 985 ┆ 81  ┆ 011 ┆ 235 ┆ 946 ┆ 629 ┆ 142 ┆ 569 ┆ 803 ┆ 72  ┆ 32  ┆ 36  ┆ 08  ┆ 952 │
│     ┆     ┆ EV  ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ VAL ┆ COL ┆ R   ┆ EV  ┆ 764 ┆ 0.1 ┆ 0.1 ┆ 0.8 ┆ -0. ┆ -0. ┆ -0. ┆ 41. ┆ 33. ┆ 739 ┆ 16. ┆ 21. ┆ 687 ┆ 25. ┆ 11. ┆ 52. ┆ 3.2 ┆ 2.5 ┆ 57. ┆ 1.2 ┆ 1.7 ┆ 53. ┆ 1.9 ┆ 0.8 ┆ 4.0 ┆ 0.4 ┆ 1.7 ┆ 0.4 ┆ 1.3 ┆ 1.2 ┆ 0.6 ┆ -2. ┆ -3. ┆ -1. ┆ 1.0 ┆ 0.8 ┆ 0.8 ┆ -0. ┆ 0.1 ┆ 0.7 ┆ 2.8 ┆ 2.2 ┆ 0.9 ┆ 0.8 ┆ 0.5 ┆ 0.3 ┆ -0. ┆ -1. ┆ -0. ┆ 1.5 ┆ 1.3 ┆ 0.3 ┆ 3.0 ┆ 1.1 ┆ 2.9 │
│ 920 ┆     ┆ ERI ┆     ┆     ┆     ┆ .88 ┆ 662 ┆ 619 ┆ 110 ┆ 258 ┆ 315 ┆ 966 ┆ 0   ┆ 069 ┆ .0  ┆ 0   ┆ 706 ┆ .0  ┆ 0   ┆ 362 ┆ 0   ┆ 161 ┆ 940 ┆ 969 ┆ 550 ┆ 026 ┆ 890 ┆ 610 ┆ 913 ┆ 790 ┆ 770 ┆ 777 ┆ 252 ┆ 449 ┆ 576 ┆ 625 ┆ 959 ┆ 471 ┆ 024 ┆ 511 ┆ 078 ┆ 332 ┆ 226 ┆ 576 ┆ 189 ┆ 460 ┆ 299 ┆ 077 ┆ 304 ┆ 768 ┆ 954 ┆ 954 ┆ 336 ┆ 076 ┆ 582 ┆ 773 ┆ 541 ┆ 028 ┆ 630 ┆ 836 │
│ 20  ┆     ┆ .NI ┆     ┆     ┆     ┆ 333 ┆ 43  ┆ 13  ┆ 15  ┆ 969 ┆ 143 ┆ 763 ┆     ┆ 035 ┆     ┆     ┆ 045 ┆     ┆     ┆ 99  ┆     ┆ 77  ┆ 45  ┆ 625 ┆ 93  ┆ 95  ┆ 572 ┆ 83  ┆ 51  ┆ 53  ┆ 56  ┆ 78  ┆ 12  ┆ 86  ┆ 09  ┆ 4   ┆ 209 ┆ 963 ┆ 562 ┆ 38  ┆ 78  ┆ 49  ┆ 083 ┆ 1   ┆ 82  ┆ 26  ┆ 89  ┆ 84  ┆ 73  ┆ 08  ┆ 62  ┆ 346 ┆ 591 ┆ 125 ┆ 34  ┆ 25  ┆ 21  ┆ 31  ┆ 76  ┆ 86  │
│     ┆     ┆ CHU ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ SHK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ IN  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ PAT ┆ BOS ┆ C   ┆ EV  ┆ 924 ┆ 0.1 ┆ 0.3 ┆ 5.2 ┆ -0. ┆ -0. ┆ -3. ┆ 51. ┆ 50. ┆ 108 ┆ 27. ┆ 25. ┆ 712 ┆ 24. ┆ 25. ┆ 369 ┆ 3.3 ┆ 3.2 ┆ 70. ┆ 1.7 ┆ 1.6 ┆ 46. ┆ 1.5 ┆ 1.6 ┆ 23. ┆ 0.6 ┆ 8.3 ┆ 0.3 ┆ 0.7 ┆ 2.5 ┆ 3.9 ┆ -2. ┆ -3. ┆ -2. ┆ 1.2 ┆ 1.4 ┆ 1.4 ┆ 0.0 ┆ 0.0 ┆ 0.5 ┆ 2.6 ┆ 4.1 ┆ 5.3 ┆ 0.6 ┆ 1.5 ┆ 2.2 ┆ -0. ┆ -1. ┆ -1. ┆ 1.1 ┆ 2.1 ┆ 2.8 ┆ 4.1 ┆ 4.6 ┆ 2.1 │
│ 120 ┆     ┆ RIC ┆     ┆     ┆     ┆ .48 ┆ 159 ┆ 222 ┆ 936 ┆ 241 ┆ 309 ┆ 045 ┆ 0   ┆ 392 ┆ 1.0 ┆ 0   ┆ 235 ┆ .0  ┆ 0   ┆ 157 ┆ .0  ┆ 099 ┆ 705 ┆ 158 ┆ 523 ┆ 377 ┆ 209 ┆ 576 ┆ 327 ┆ 948 ┆ 312 ┆ 387 ┆ 578 ┆ 336 ┆ 023 ┆ 376 ┆ 110 ┆ 354 ┆ 445 ┆ 139 ┆ 075 ┆ 475 ┆ 907 ┆ 783 ┆ 064 ┆ 514 ┆ 783 ┆ 987 ┆ 467 ┆ 283 ┆ 255 ┆ 707 ┆ 406 ┆ 369 ┆ 548 ┆ 753 ┆ 451 ┆ 296 ┆ 506 ┆ 823 │
│ 22  ┆     ┆ E.B ┆     ┆     ┆     ┆ 333 ┆ 87  ┆ 92  ┆ 67  ┆ 82  ┆ 005 ┆ 078 ┆     ┆ 319 ┆     ┆     ┆ 159 ┆     ┆     ┆ 16  ┆     ┆ 57  ┆ 18  ┆ 106 ┆ 3   ┆ 9   ┆ 595 ┆ 27  ┆ 28  ┆ 512 ┆ 97  ┆ 45  ┆ 07  ┆ 92  ┆ 14  ┆ 7   ┆ 5   ┆ 103 ┆ 511 ┆ 6   ┆     ┆ 81  ┆ 61  ┆ 14  ┆ 31  ┆ 49  ┆ 22  ┆ 92  ┆ 82  ┆ 44  ┆ 98  ┆ 419 ┆ 495 ┆ 892 ┆ 2   ┆ 93  ┆ 3   ┆ 93  ┆ 8   ┆ 32  │
│     ┆     ┆ ERG ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ERO ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ N   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [ ]:
# Followed by top regular season, even strength offensive players, all-time
rapm_results.filter(filter_conditions).sort(pl.col("off_coeff_xg_z"), descending=True).head(10)

shape: (10, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sea ┆ ses ┆ pla ┆ tea ┆ pos ┆ sit ┆ toi ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot ┆ off ┆ off ┆ off ┆ def ┆ def ┆ def ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ met ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ on_ ┆ tot ┆ tot ┆ tot │
│ son ┆ sio ┆ yer ┆ m   ┆ --- ┆ uat ┆ _mi ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ _co ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ric ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ ice ┆ al_ ┆ al_ ┆ al_ │
│ --- ┆ n   ┆ --- ┆ --- ┆ str ┆ ion ┆ nut ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ eff ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ _fo ┆ _fo ┆ _fo ┆ _ag ┆ _ag ┆ _ag ┆ _di ┆ _di ┆ _di ┆ rap ┆ rap ┆ rap │
│ i32 ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ es  ┆ _go ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ r_g ┆ r_x ┆ r_c ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g ┆ _go ┆ _xg ┆ _co ┆ _go ┆ _xg ┆ _co ┆ r_g ┆ r_x ┆ r_c ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ r_6 ┆ r_6 ┆ r_6 ┆ ain ┆ ain ┆ ain ┆ ff_ ┆ ff_ ┆ ff_ ┆ m_x ┆ m_c ┆ m_g │
│     ┆ str ┆     ┆     ┆     ┆ str ┆ --- ┆ als ┆ --- ┆ rsi ┆ als ┆ --- ┆ rsi ┆ oal ┆ g   ┆ ors ┆ st_ ┆ st_ ┆ st_ ┆ goa ┆ xg  ┆ cor ┆ 0_g ┆ 0_x ┆ 0_c ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g   ┆ ors ┆ oal ┆ als ┆ _z  ┆ rsi ┆ als ┆ _z  ┆ rsi ┆ oal ┆ g_z ┆ ors ┆ st_ ┆ st_ ┆ st_ ┆ goa ┆ xg_ ┆ cor ┆ 0_g ┆ 0_x ┆ 0_c ┆ st_ ┆ st_ ┆ st_ ┆ 60_ ┆ 60_ ┆ 60_ ┆ g_z ┆ ors ┆ oal │
│     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ s   ┆ --- ┆ i   ┆ goa ┆ xg  ┆ cor ┆ ls  ┆ --- ┆ si  ┆ oal ┆ g   ┆ ors ┆ 60_ ┆ 60_ ┆ 60_ ┆ goa ┆ xg  ┆ cor ┆ --- ┆ i   ┆ s   ┆ _z  ┆ --- ┆ _z  ┆ _z  ┆ --- ┆ _z  ┆ s_z ┆ --- ┆ i_z ┆ goa ┆ xg_ ┆ cor ┆ ls_ ┆ z   ┆ si_ ┆ oal ┆ g_z ┆ ors ┆ 60_ ┆ 60_ ┆ 60_ ┆ goa ┆ xg_ ┆ cor ┆ --- ┆ i_z ┆ s_z │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ ls  ┆ --- ┆ si  ┆ --- ┆ f64 ┆ --- ┆ s   ┆ --- ┆ i   ┆ goa ┆ xg  ┆ cor ┆ ls  ┆ --- ┆ si  ┆ f64 ┆ --- ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ ls_ ┆ z   ┆ si_ ┆ z   ┆ --- ┆ z   ┆ s_z ┆ --- ┆ i_z ┆ goa ┆ xg_ ┆ cor ┆ ls_ ┆ z   ┆ si_ ┆ f64 ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ ls  ┆ --- ┆ si  ┆ --- ┆ f64 ┆ --- ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ z   ┆ --- ┆ z   ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ --- ┆ ls_ ┆ z   ┆ si_ ┆ z   ┆ --- ┆ z   ┆     ┆ f64 ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆ z   ┆ --- ┆ z   ┆ --- ┆ f64 ┆ --- ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ R   ┆ CON ┆ EDM ┆ C   ┆ EV  ┆ 139 ┆ 0.3 ┆ 0.6 ┆ 5.4 ┆ -0. ┆ -0. ┆ -0. ┆ 80. ┆ 85. ┆ 149 ┆ 54. ┆ 61. ┆ 131 ┆ 26. ┆ 23. ┆ 175 ┆ 3.4 ┆ 3.6 ┆ 64. ┆ 2.3 ┆ 2.6 ┆ 56. ┆ 1.1 ┆ 1.0 ┆ 7.5 ┆ 0.6 ┆ 6.1 ┆ 0.5 ┆ 2.5 ┆ 5.2 ┆ 4.0 ┆ -1. ┆ -0. ┆ -0. ┆ 2.5 ┆ 3.2 ┆ 2.5 ┆ 1.4 ┆ 2.1 ┆ 2.1 ┆ 2.8 ┆ 3.9 ┆ 2.5 ┆ 0.7 ┆ 2.2 ┆ 1.4 ┆ -0. ┆ 0.2 ┆ 0.3 ┆ 0.8 ┆ 1.4 ┆ 0.9 ┆ 4.4 ┆ 3.4 ┆ 3.1 │
│ 120 ┆     ┆ NOR ┆     ┆     ┆     ┆ 4.4 ┆ 976 ┆ 739 ┆ 727 ┆ 118 ┆ 011 ┆ 700 ┆ 0   ┆ 735 ┆ 3.0 ┆ 0   ┆ 807 ┆ 8.0 ┆ 0   ┆ 928 ┆ .0  ┆ 421 ┆ 889 ┆ 239 ┆ 234 ┆ 593 ┆ 709 ┆ 187 ┆ 295 ┆ 297 ┆ 853 ┆ 735 ┆ 161 ┆ 709 ┆ 375 ┆ 695 ┆ 095 ┆ 211 ┆ 515 ┆ 465 ┆ 628 ┆ 115 ┆ 678 ┆ 387 ┆ 107 ┆ 666 ┆ 764 ┆ 624 ┆ 340 ┆ 053 ┆ 254 ┆ 278 ┆ 297 ┆ 023 ┆ 909 ┆ 555 ┆ 813 ┆ 785 ┆ 399 ┆ 194 │
│ 22  ┆     ┆ .MC ┆     ┆     ┆     ┆ 666 ┆ 33  ┆ 87  ┆ 45  ┆ 531 ┆ 333 ┆ 795 ┆     ┆ 67  ┆     ┆     ┆ 032 ┆     ┆     ┆ 638 ┆     ┆ 76  ┆ 66  ┆ 614 ┆ 69  ┆ 84  ┆ 853 ┆ 07  ┆ 82  ┆ 6   ┆ 2   ┆ 4   ┆ 64  ┆ 62  ┆ 08  ┆ 36  ┆ 333 ┆ 794 ┆ 084 ┆ 71  ┆ 85  ┆ 06  ┆ 76  ┆ 98  ┆ 23  ┆ 77  ┆     ┆ 92  ┆ 59  ┆     ┆ 5   ┆ 1   ┆ 95  ┆ 17  ┆ 53  ┆ 95  ┆ 7   ┆ 64  ┆ 87  ┆ 34  │
│     ┆     ┆ DAV ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ID  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ MAT ┆ FLA ┆ L   ┆ EV  ┆ 116 ┆ 0.6 ┆ 0.8 ┆ 6.7 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ 92. ┆ 82. ┆ 136 ┆ 54. ┆ 56. ┆ 114 ┆ 38. ┆ 26. ┆ 213 ┆ 4.7 ┆ 4.2 ┆ 70. ┆ 2.7 ┆ 2.9 ┆ 59. ┆ 1.9 ┆ 1.3 ┆ 10. ┆ 0.8 ┆ 7.1 ┆ 0.5 ┆ 5.5 ┆ 4.9 ┆ 4.8 ┆ 0.6 ┆ 0.2 ┆ -0. ┆ 3.3 ┆ 2.9 ┆ 2.1 ┆ 1.7 ┆ 1.8 ┆ 1.7 ┆ 4.1 ┆ 4.1 ┆ 3.4 ┆ 2.2 ┆ 1.9 ┆ 1.6 ┆ 0.0 ┆ 0.3 ┆ 0.3 ┆ 1.3 ┆ 1.2 ┆ 1.1 ┆ 3.9 ┆ 4.4 ┆ 4.3 │
│ 220 ┆     ┆ THE ┆     ┆     ┆     ┆ 5.6 ┆ 281 ┆ 935 ┆ 881 ┆ 594 ┆ 418 ┆ 347 ┆ 0   ┆ 705 ┆ 0.0 ┆ 0   ┆ 536 ┆ 7.0 ┆ 0   ┆ 168 ┆ .0  ┆ 355 ┆ 571 ┆ 003 ┆ 795 ┆ 101 ┆ 040 ┆ 559 ┆ 469 ┆ 963 ┆ 516 ┆ 358 ┆ 686 ┆ 531 ┆ 966 ┆ 490 ┆ 299 ┆ 614 ┆ 318 ┆ 620 ┆ 671 ┆ 807 ┆ 218 ┆ 767 ┆ 290 ┆ 352 ┆ 472 ┆ 424 ┆ 945 ┆ 743 ┆ 074 ┆ 907 ┆ 163 ┆ 731 ┆ 329 ┆ 412 ┆ 802 ┆ 996 ┆ 438 ┆ 873 │
│ 23  ┆     ┆ W.T ┆     ┆     ┆     ┆ 5   ┆ 56  ┆ 19  ┆ 46  ┆ 58  ┆ 57  ┆ 7   ┆     ┆ 709 ┆     ┆     ┆ 985 ┆     ┆     ┆ 724 ┆     ┆ 55  ┆ 46  ┆ 861 ┆ 65  ┆ 52  ┆ 021 ┆ 9   ┆ 94  ┆ 84  ┆ 62  ┆ 45  ┆ 98  ┆ 91  ┆ 91  ┆ 43  ┆ 72  ┆ 31  ┆ 84  ┆ 1   ┆ 08  ┆ 59  ┆ 53  ┆     ┆ 21  ┆ 63  ┆ 68  ┆ 65  ┆ 21  ┆ 57  ┆ 32  ┆ 45  ┆ 1   ┆ 33  ┆ 98  ┆ 99  ┆ 01  ┆ 18  ┆ 87  ┆ 92  │
│     ┆     ┆ KAC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ HUK ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ CON ┆ EDM ┆ C   ┆ EV  ┆ 140 ┆ 0.6 ┆ 0.6 ┆ 4.5 ┆ 0.0 ┆ 0.2 ┆ 1.2 ┆ 87. ┆ 82. ┆ 155 ┆ 64. ┆ 69. ┆ 139 ┆ 23. ┆ 12. ┆ 159 ┆ 3.7 ┆ 3.5 ┆ 66. ┆ 2.7 ┆ 2.9 ┆ 59. ┆ 0.9 ┆ 0.5 ┆ 6.8 ┆ 0.3 ┆ 3.2 ┆ 0.6 ┆ 3.8 ┆ 4.8 ┆ 3.2 ┆ 0.0 ┆ 2.5 ┆ 1.0 ┆ 2.9 ┆ 2.9 ┆ 2.2 ┆ 2.0 ┆ 2.4 ┆ 1.9 ┆ 2.2 ┆ 2.7 ┆ 2.6 ┆ 1.2 ┆ 2.4 ┆ 1.5 ┆ 0.3 ┆ 1.1 ┆ 0.4 ┆ 0.7 ┆ 1.0 ┆ 0.8 ┆ 2.7 ┆ 1.9 ┆ 3.1 │
│ 720 ┆     ┆ NOR ┆     ┆     ┆     ┆ 0.2 ┆ 291 ┆ 178 ┆ 041 ┆ 149 ┆ 489 ┆ 428 ┆ 0   ┆ 456 ┆ 5.0 ┆ 0   ┆ 528 ┆ 6.0 ┆ 0   ┆ 928 ┆ .0  ┆ 279 ┆ 332 ┆ 631 ┆ 424 ┆ 792 ┆ 818 ┆ 855 ┆ 539 ┆ 131 ┆ 689 ┆ 613 ┆ 141 ┆ 755 ┆ 845 ┆ 294 ┆ 812 ┆ 412 ┆ 067 ┆ 074 ┆ 976 ┆ 936 ┆ 882 ┆ 531 ┆ 573 ┆ 887 ┆ 279 ┆ 822 ┆ 262 ┆ 686 ┆ 499 ┆ 842 ┆ 947 ┆ 351 ┆ 053 ┆ 454 ┆ 697 ┆ 005 ┆ 054 ┆ 507 │
│ 18  ┆     ┆ .MC ┆     ┆     ┆     ┆ 333 ┆ 81  ┆ 71  ┆ 92  ┆ 89  ┆ 43  ┆ 42  ┆     ┆ 034 ┆     ┆     ┆ 03  ┆     ┆     ┆ 003 ┆     ┆ 5   ┆ 41  ┆ 752 ┆     ┆ 76  ┆ 602 ┆ 5   ┆ 65  ┆ 5   ┆ 28  ┆ 5   ┆ 92  ┆ 69  ┆ 21  ┆ 98  ┆ 01  ┆ 51  ┆ 21  ┆ 38  ┆ 98  ┆ 41  ┆ 66  ┆ 72  ┆ 03  ┆ 81  ┆ 47  ┆ 29  ┆ 41  ┆ 41  ┆ 41  ┆ 38  ┆ 13  ┆ 94  ┆ 31  ┆ 11  ┆ 55  ┆ 51  ┆ 29  ┆ 95  │
│     ┆     ┆ DAV ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ID  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ JOH ┆ NYI ┆ C   ┆ EV  ┆ 138 ┆ 0.2 ┆ 0.5 ┆ 2.9 ┆ 0.1 ┆ 0.0 ┆ 1.1 ┆ 66. ┆ 75. ┆ 137 ┆ 66. ┆ 61. ┆ 131 ┆ 0.0 ┆ 13. ┆ 59. ┆ 2.8 ┆ 3.2 ┆ 59. ┆ 2.8 ┆ 2.6 ┆ 57. ┆ 0.0 ┆ 0.6 ┆ 2.5 ┆ 0.4 ┆ 1.7 ┆ 0.0 ┆ 1.9 ┆ 4.5 ┆ 2.1 ┆ 1.6 ┆ 0.8 ┆ 0.9 ┆ 2.2 ┆ 3.0 ┆ 2.1 ┆ 2.5 ┆ 2.4 ┆ 2.0 ┆ -0. ┆ 2.7 ┆ 0.9 ┆ 0.8 ┆ 2.3 ┆ 0.9 ┆ 0.7 ┆ 0.9 ┆ 0.5 ┆ 0.1 ┆ 1.0 ┆ 0.3 ┆ 3.2 ┆ 1.0 ┆ 0.6 │
│ 120 ┆     ┆ N.T ┆     ┆     ┆     ┆ 2.0 ┆ 209 ┆ 510 ┆ 064 ┆ 344 ┆ 797 ┆ 401 ┆ 0   ┆ 426 ┆ 8.0 ┆ 0   ┆ 566 ┆ 9.0 ┆     ┆ 860 ┆ 0   ┆ 652 ┆ 744 ┆ 822 ┆ 652 ┆ 727 ┆ 261 ┆     ┆ 017 ┆ 613 ┆ 713 ┆ 662 ┆ 865 ┆ 412 ┆ 317 ┆ 728 ┆ 046 ┆ 698 ┆ 374 ┆ 564 ┆ 440 ┆ 902 ┆ 727 ┆ 240 ┆ 889 ┆ 021 ┆ 557 ┆ 817 ┆ 745 ┆ 130 ┆ 873 ┆ 172 ┆ 027 ┆ 188 ┆ 608 ┆ 543 ┆ 112 ┆ 086 ┆ 212 ┆ 424 │
│ 12  ┆     ┆ AVA ┆     ┆     ┆     ┆ 833 ┆ 86  ┆ 2   ┆ 26  ┆ 63  ┆ 14  ┆ 96  ┆     ┆ 779 ┆     ┆     ┆ 216 ┆     ┆     ┆ 563 ┆     ┆ 4   ┆ 82  ┆ 731 ┆ 4   ┆ 57  ┆ 381 ┆     ┆ 25  ┆ 51  ┆ 05  ┆ 3   ┆ 23  ┆ 57  ┆ 27  ┆ 41  ┆ 62  ┆ 82  ┆ 96  ┆ 68  ┆ 1   ┆ 67  ┆ 62  ┆ 81  ┆ 68  ┆ 564 ┆ 39  ┆ 88  ┆ 18  ┆ 28  ┆ 45  ┆ 9   ┆ 48  ┆ 93  ┆ 31  ┆ 94  ┆ 35  ┆ 36  ┆ 42  ┆ 43  │
│     ┆     ┆ RES ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ CON ┆ EDM ┆ C   ┆ EV  ┆ 959 ┆ 0.5 ┆ 0.4 ┆ 4.2 ┆ 0.2 ┆ 0.0 ┆ 0.2 ┆ 66. ┆ 52. ┆ 975 ┆ 51. ┆ 40. ┆ 910 ┆ 15. ┆ 12. ┆ 65. ┆ 4.1 ┆ 3.3 ┆ 60. ┆ 3.1 ┆ 2.5 ┆ 56. ┆ 0.9 ┆ 0.7 ┆ 4.0 ┆ 0.4 ┆ 3.9 ┆ 0.3 ┆ 4.2 ┆ 4.4 ┆ 3.5 ┆ 2.0 ┆ 0.2 ┆ 0.2 ┆ 3.5 ┆ 3.1 ┆ 2.4 ┆ 2.8 ┆ 2.3 ┆ 2.2 ┆ 1.9 ┆ 2.9 ┆ 1.5 ┆ 1.5 ┆ 2.1 ┆ 1.4 ┆ 0.5 ┆ 0.4 ┆ 0.5 ┆ 0.6 ┆ 1.2 ┆ 0.6 ┆ 3.2 ┆ 2.5 ┆ 1.9 │
│ 020 ┆     ┆ NOR ┆     ┆     ┆     ┆ .45 ┆ 411 ┆ 808 ┆ 051 ┆ 247 ┆ 299 ┆ 173 ┆ 0   ┆ 852 ┆ .0  ┆ 0   ┆ 847 ┆ .0  ┆ 0   ┆ 004 ┆ 0   ┆ 273 ┆ 051 ┆ 972 ┆ 893 ┆ 544 ┆ 907 ┆ 380 ┆ 507 ┆ 648 ┆ 508 ┆ 878 ┆ 163 ┆ 364 ┆ 107 ┆ 729 ┆ 501 ┆ 866 ┆ 080 ┆ 432 ┆ 305 ┆ 500 ┆ 383 ┆ 043 ┆ 444 ┆ 781 ┆ 794 ┆ 471 ┆ 786 ┆ 870 ┆ 238 ┆ 624 ┆ 102 ┆ 746 ┆ 133 ┆ 198 ┆ 173 ┆ 932 ┆ 705 ┆ 331 │
│ 21  ┆     ┆ .MC ┆     ┆     ┆     ┆     ┆ 02  ┆ 18  ┆ 18  ┆ 12  ┆ 72  ┆ 01  ┆     ┆ 726 ┆     ┆     ┆ 974 ┆     ┆     ┆ 751 ┆     ┆ 65  ┆ 89  ┆ 432 ┆ 27  ┆ 62  ┆ 603 ┆ 37  ┆ 27  ┆ 29  ┆ 46  ┆ 17  ┆ 9   ┆ 25  ┆ 79  ┆ 83  ┆ 96  ┆ 16  ┆ 7   ┆ 36  ┆ 03  ┆ 48  ┆ 41  ┆ 27  ┆ 26  ┆ 45  ┆ 05  ┆ 53  ┆ 22  ┆ 41  ┆ 37  ┆ 89  ┆ 78  ┆ 85  ┆ 64  ┆ 19  ┆ 32  ┆ 93  ┆ 75  ┆ 03  │
│     ┆     ┆ DAV ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ID  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ DAM ┆ NJD ┆ D   ┆ EV  ┆ 140 ┆ -0. ┆ 0.5 ┆ 3.1 ┆ -0. ┆ -0. ┆ 0.3 ┆ 61. ┆ 84. ┆ 147 ┆ 53. ┆ 57. ┆ 132 ┆ 8.0 ┆ 27. ┆ 154 ┆ 2.6 ┆ 3.6 ┆ 63. ┆ 2.2 ┆ 2.4 ┆ 56. ┆ 0.3 ┆ 1.1 ┆ 6.5 ┆ 0.6 ┆ 2.7 ┆ 0.0 ┆ -0. ┆ 4.3 ┆ 2.3 ┆ -0. ┆ -0. ┆ 0.2 ┆ 1.1 ┆ 2.1 ┆ 1.5 ┆ 0.9 ┆ 1.0 ┆ 1.2 ┆ 0.7 ┆ 3.4 ┆ 1.9 ┆ 0.1 ┆ 1.9 ┆ 1.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ 1.5 ┆ 0.7 ┆ 3.3 ┆ 1.5 ┆ 0.2 │
│ 220 ┆     ┆ ON. ┆     ┆     ┆     ┆ 3.7 ┆ 037 ┆ 891 ┆ 504 ┆ 063 ┆ 069 ┆ 510 ┆ 0   ┆ 325 ┆ 6.0 ┆ 0   ┆ 283 ┆ 2.0 ┆     ┆ 042 ┆ .0  ┆ 073 ┆ 043 ┆ 088 ┆ 653 ┆ 484 ┆ 506 ┆ 419 ┆ 558 ┆ 824 ┆ 591 ┆ 993 ┆ 254 ┆ 362 ┆ 425 ┆ 873 ┆ 690 ┆ 550 ┆ 966 ┆ 782 ┆ 266 ┆ 739 ┆ 059 ┆ 737 ┆ 943 ┆ 233 ┆ 483 ┆ 729 ┆ 901 ┆ 313 ┆ 658 ┆ 399 ┆ 447 ┆ 048 ┆ 942 ┆ 156 ┆ 917 ┆ 804 ┆ 024 ┆ 048 │
│ 23  ┆     ┆ SEV ┆     ┆     ┆     ┆ 333 ┆ 618 ┆ 48  ┆ 73  ┆ 029 ┆ 955 ┆ 85  ┆     ┆ 926 ┆     ┆     ┆ 913 ┆     ┆     ┆ 013 ┆     ┆ 33  ┆ 57  ┆ 906 ┆ 88  ┆ 96  ┆ 459 ┆ 45  ┆ 61  ┆ 47  ┆ 04  ┆ 88  ┆ 11  ┆ 19  ┆ 35  ┆ 18  ┆ 799 ┆ 102 ┆ 82  ┆ 14  ┆ 12  ┆ 87  ┆ 84  ┆ 23  ┆ 83  ┆ 46  ┆ 03  ┆ 88  ┆ 25  ┆ 88  ┆ 32  ┆ 774 ┆ 985 ┆ 738 ┆ 03  ┆ 45  ┆ 69  ┆ 8   ┆ 83  ┆ 29  │
│     ┆     ┆ ERS ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ ON  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ AUS ┆ TOR ┆ C   ┆ EV  ┆ 123 ┆ 0.5 ┆ 0.5 ┆ 4.2 ┆ 0.1 ┆ -0. ┆ -2. ┆ 95. ┆ 77. ┆ 132 ┆ 67. ┆ 45. ┆ 108 ┆ 28. ┆ 31. ┆ 237 ┆ 4.6 ┆ 3.7 ┆ 64. ┆ 3.2 ┆ 2.2 ┆ 52. ┆ 1.3 ┆ 1.5 ┆ 11. ┆ 0.7 ┆ 6.9 ┆ 0.4 ┆ 3.7 ┆ 4.3 ┆ 3.1 ┆ 1.0 ┆ -1. ┆ -2. ┆ 3.2 ┆ 2.8 ┆ 2.0 ┆ 2.1 ┆ 1.2 ┆ 1.4 ┆ 3.0 ┆ 5.2 ┆ 3.4 ┆ 1.5 ┆ 2.3 ┆ 1.4 ┆ 0.4 ┆ -0. ┆ -0. ┆ 1.0 ┆ 2.0 ┆ 1.4 ┆ 4.6 ┆ 3.8 ┆ 2.6 │
│ 120 ┆     ┆ TON ┆     ┆     ┆     ┆ 2.2 ┆ 816 ┆ 583 ┆ 444 ┆ 459 ┆ 151 ┆ 729 ┆ 0   ┆ 477 ┆ 3.0 ┆ 0   ┆ 630 ┆ 6.0 ┆ 0   ┆ 847 ┆ .0  ┆ 257 ┆ 725 ┆ 419 ┆ 623 ┆ 218 ┆ 879 ┆ 633 ┆ 507 ┆ 540 ┆ 102 ┆ 744 ┆ 357 ┆ 714 ┆ 380 ┆ 650 ┆ 824 ┆ 695 ┆ 186 ┆ 358 ┆ 293 ┆ 725 ┆ 309 ┆ 273 ┆ 965 ┆ 819 ┆ 779 ┆ 689 ┆ 153 ┆ 405 ┆ 497 ┆ 276 ┆ 471 ┆ 307 ┆ 380 ┆ 775 ┆ 365 ┆ 392 ┆ 878 ┆ 433 │
│ 22  ┆     ┆ .MA ┆     ┆     ┆     ┆ 333 ┆ 63  ┆ 32  ┆ 25  ┆ 5   ┆ 876 ┆ 986 ┆     ┆ 53  ┆     ┆     ┆ 05  ┆     ┆     ┆ 48  ┆     ┆ 47  ┆ 42  ┆ 617 ┆ 69  ┆ 22  ┆ 595 ┆ 78  ┆ 2   ┆ 022 ┆ 09  ┆ 11  ┆ 13  ┆ 48  ┆ 42  ┆ 51  ┆ 23  ┆ 408 ┆ 045 ┆ 53  ┆ 66  ┆ 08  ┆ 31  ┆ 76  ┆ 38  ┆ 06  ┆ 53  ┆ 38  ┆ 28  ┆ 07  ┆ 85  ┆ 6   ┆ 049 ┆ 667 ┆ 43  ┆ 24  ┆ 91  ┆ 91  ┆ 01  ┆ 53  │
│     ┆     ┆ TTH ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆ EWS ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 201 ┆ R   ┆ BRE ┆ SJS ┆ D   ┆ EV  ┆ 155 ┆ 0.3 ┆ 0.4 ┆ 5.3 ┆ -0. ┆ 0.1 ┆ 1.9 ┆ 82. ┆ 76. ┆ 169 ┆ 53. ┆ 66. ┆ 154 ┆ 29. ┆ 10. ┆ 153 ┆ 3.1 ┆ 2.9 ┆ 65. ┆ 2.0 ┆ 2.5 ┆ 59. ┆ 1.1 ┆ 0.4 ┆ 5.9 ┆ 0.3 ┆ 3.3 ┆ 0.4 ┆ 3.8 ┆ 4.2 ┆ 4.9 ┆ -0. ┆ 1.0 ┆ 1.7 ┆ 2.3 ┆ 2.1 ┆ 1.9 ┆ 1.1 ┆ 1.7 ┆ 1.7 ┆ 3.0 ┆ 1.9 ┆ 2.4 ┆ 0.7 ┆ 1.7 ┆ 2.0 ┆ -0. ┆ 0.4 ┆ 0.6 ┆ 0.6 ┆ 0.7 ┆ 0.7 ┆ 2.3 ┆ 2.5 ┆ 3.4 │
│ 620 ┆     ┆ NT. ┆     ┆     ┆     ┆ 1.6 ┆ 725 ┆ 301 ┆ 219 ┆ 064 ┆ 166 ┆ 283 ┆ 0   ┆ 842 ┆ 5.0 ┆ 0   ┆ 326 ┆ 2.0 ┆ 0   ┆ 515 ┆ .0  ┆ 709 ┆ 714 ┆ 545 ┆ 494 ┆ 648 ┆ 628 ┆ 214 ┆ 066 ┆ 164 ┆ 135 ┆ 935 ┆ 371 ┆ 926 ┆ 684 ┆ 680 ┆ 819 ┆ 181 ┆ 85  ┆ 407 ┆ 616 ┆ 968 ┆ 080 ┆ 123 ┆ 026 ┆ 298 ┆ 795 ┆ 165 ┆ 482 ┆ 656 ┆ 263 ┆ 274 ┆ 000 ┆ 817 ┆ 921 ┆ 912 ┆ 980 ┆ 856 ┆ 478 ┆ 475 │
│ 17  ┆     ┆ BUR ┆     ┆     ┆     ┆     ┆ 76  ┆ 92  ┆ 25  ┆ 576 ┆ 68  ┆ 82  ┆     ┆ 656 ┆     ┆     ┆ 767 ┆     ┆     ┆ 888 ┆     ┆ 2   ┆ 87  ┆ 244 ┆ 97  ┆ 4   ┆ 77  ┆ 23  ┆ 47  ┆ 73  ┆ 24  ┆ 43  ┆ 52  ┆ 31  ┆ 97  ┆ 11  ┆ 069 ┆ 16  ┆     ┆ 21  ┆     ┆ 98  ┆ 87  ┆ 01  ┆ 85  ┆ 46  ┆ 72  ┆ 66  ┆ 14  ┆ 24  ┆ 06  ┆ 146 ┆ 03  ┆ 12  ┆ 18  ┆ 79  ┆ 07  ┆ 46  ┆ 26  ┆ 51  │
│     ┆     ┆ NS  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ R   ┆ NAT ┆ COL ┆ C   ┆ EV  ┆ 144 ┆ 0.5 ┆ 0.5 ┆ 5.6 ┆ 0.0 ┆ -0. ┆ 0.3 ┆ 106 ┆ 81. ┆ 164 ┆ 69. ┆ 59. ┆ 146 ┆ 37. ┆ 21. ┆ 184 ┆ 4.4 ┆ 3.3 ┆ 68. ┆ 2.8 ┆ 2.4 ┆ 60. ┆ 1.5 ┆ 0.8 ┆ 7.6 ┆ 0.6 ┆ 5.3 ┆ 0.5 ┆ 4.4 ┆ 4.2 ┆ 3.7 ┆ 0.6 ┆ -1. ┆ 0.3 ┆ 3.5 ┆ 2.5 ┆ 2.3 ┆ 2.1 ┆ 1.7 ┆ 2.0 ┆ 3.4 ┆ 3.1 ┆ 2.5 ┆ 1.8 ┆ 1.5 ┆ 1.3 ┆ 0.3 ┆ -0. ┆ 0.3 ┆ 1.0 ┆ 1.2 ┆ 0.8 ┆ 4.0 ┆ 2.9 ┆ 3.3 │
│ 320 ┆     ┆ HAN ┆     ┆     ┆     ┆ 4.7 ┆ 704 ┆ 848 ┆ 639 ┆ 663 ┆ 111 ┆ 639 ┆ .0  ┆ 044 ┆ 5.0 ┆ 0   ┆ 385 ┆ 1.0 ┆ 0   ┆ 659 ┆ .0  ┆ 020 ┆ 656 ┆ 314 ┆ 654 ┆ 661 ┆ 673 ┆ 365 ┆ 994 ┆ 412 ┆ 960 ┆ 000 ┆ 041 ┆ 323 ┆ 111 ┆ 961 ┆ 297 ┆ 067 ┆ 247 ┆ 030 ┆ 910 ┆ 535 ┆ 657 ┆ 127 ┆ 012 ┆ 476 ┆ 005 ┆ 927 ┆ 476 ┆ 329 ┆ 501 ┆ 329 ┆ 024 ┆ 605 ┆ 893 ┆ 097 ┆ 888 ┆ 088 ┆ 484 ┆ 378 │
│ 24  ┆     ┆ .MA ┆     ┆     ┆     ┆ 833 ┆ 64  ┆ 95  ┆ 89  ┆ 23  ┆ 162 ┆ 59  ┆     ┆ 365 ┆     ┆     ┆ 343 ┆     ┆     ┆ 022 ┆     ┆ 44  ┆ 69  ┆ 742 ┆ 82  ┆ 97  ┆ 457 ┆ 63  ┆ 71  ┆ 84  ┆ 57  ┆ 3   ┆ 41  ┆ 91  ┆ 4   ┆ 85  ┆ 74  ┆ 194 ┆ 35  ┆ 91  ┆ 49  ┆ 48  ┆ 59  ┆ 33  ┆ 04  ┆ 23  ┆ 4   ┆ 39  ┆ 97  ┆ 95  ┆ 01  ┆ 18  ┆ 071 ┆ 91  ┆ 51  ┆ 15  ┆ 01  ┆ 29  ┆ 34  ┆ 61  │